### ISSUE TITLE
Not getting the autoload.php

### ISSUE THREAD

**Issue by mahiagit** [JeremyDunn/php-fedex-api-wrapper#1]
Hello Jeremy,

It seems a wonderful wrapper but unfortunately didn't overcome the Bootstrap errors as not found the autoload.php.

Working environment  Php > 5.3 and ilance architecture

Kindly update to figure out from this situation

Thanks
Mohinder Singh

**Comment by pustelaraj** [comment]
Hi Jeremy Dunn,
 composer require jeremy-dunn/php-fedex-api-wrapper
when i install this package while am getting 
below errror  am  not able to resolve this pls help me.
Check https://getcomposer.org/doc/articles/troubleshooting.md
memory errors.PS D:\xampp\htdocs\ATSFARMCART-ESITES\shoeszone

am using:
Laravel 6.0.3
php 7.1.3

Thanks
