### ISSUE TITLE
Class 'CreatePendingShipmentRequest' not found

### ISSUE THREAD

**Issue by MURL1DHAR** [JeremyDunn/php-fedex-api-wrapper#100]
I tried to run one of the examples (https://github.com/JeremyDunn/php-fedex-api-wrapper/blob/master/examples/create-pending-shipment.php) of creating a pending shipment request in Laravel. 

But php throws an error: 'Class 'FedEx\ShipService\ComplexType\CreatePendingShipmentRequest' not found'. I myself tried to find the class in the src folder but it seems to be missing. Can you update the library with the missing file?

**Comment by harikt** [comment]
My understanding is `CreateOpenShipmentRequest` is same as `CreatePendingShipmentRequest` . See https://github.com/JeremyDunn/php-fedex-api-wrapper/blob/d7a66346c5eef5977a407c0fc52dea5edbd26840/src/FedEx/_wsdl/OpenshipService_v15.wsdl#L15 . The code seems generated from wsdl.

**Comment by ThomasVeld** [comment]
Any update?
