### ISSUE TITLE
Add Ref or Inv to SHIP.php

### ISSUE THREAD

**Issue by webdevNYC** [JeremyDunn/php-fedex-api-wrapper#101]
Hi there,  thank you for your library, its great!!  
Im trying to add the order number into the Ref.: on the label. I tried to use the setCustomerReferences but didn't work.  Can you please help me with that?

Thanks a lot.

**Comment by graffxdesign** [comment]
Were you able to fix it? I am having the same issue

**Comment by NiZerin** [comment]
so sad, i have same issue now
