### ISSUE TITLE
Example for creating a notification request

### ISSUE THREAD

**Issue by regiscamimura** [JeremyDunn/php-fedex-api-wrapper#102]
Could an example for creating a notification request on a shipment that was already created (and so using the TrackService/SendNotificationRequest) to be added?

**Comment by rmbaumer** [comment]
See this: https://github.com/JeremyDunn/php-fedex-api-wrapper/commit/e063d9ebaa6da9a8c57f08dc64964d3ceb720c99

You'll need to update the version from 14 to 16  on line 43 - otherwise that example works
