### ISSUE TITLE
Credentials.php

### ISSUE THREAD

**Issue by pushangupta** [JeremyDunn/php-fedex-api-wrapper#106]
There is no file under examples named credentials.php

**Comment by jigneshradicalloop** [comment]
rename example.credentials.php to credentials.php

**Comment by TheGr8** [comment]
When you click on "Get Your Test Key" it gives you a form where you enter your contact information and email. The password will be sent to that email after you complete that step. I wasn't getting mine, so I contacted FedEx support and they told me that it happens with some email addresses and asked me if I had a generic email address I could use (like Gmail). I did that and received the password within 1 or 2 minutes.

**Comment by nikunjsilvercayde** [comment]
> When you click on "Get Your Test Key" it gives you a form where you enter your contact information and email. The password will be sent to that email after you complete that step. I wasn't getting mine, so I contacted FedEx support and they told me that it happens with some email addresses and asked me if I had a generic email address I could use (like Gmail). I did that and received the password within 1 or 2 minutes.

Hi,
Thanks I got password in my gmail account. 

Thanks you..
