### ISSUE TITLE
Multiple-Package Shipments

### ISSUE THREAD

**Issue by mistris** [JeremyDunn/php-fedex-api-wrapper#107]
Can someone please provide an example code for creating Multiple-Package Shipment?
I need to get 1 PDF with 6 shipping labels ("1 of 6", "2 of 6", "3 of 6", "4 of 6", "5 of 6", "6 of 6") for shipment with 2 items A, 3 items B and 1 item C.
Now I'm requesting shipment for each item (6 requests). From the 1st response I get MasterTrackingId that I use in next 5 requests.
In result I get PDF that consists of 1 page showing "6 of 6" without any item description - because I return `$request->getProcessShipmentReply($processShipmentRequest)` for each package and in the end I just get PDF that contains only the last response. Is there a way to merge all these responses and get 1 shipping label? I thought that MasterTrackingId does it.

And if I try to do the same thing for only 1 item with quantity = 1 then I get back correct PDF but it consists of 5 equal pages - there should be only 1 page. I don't know where the "5" comes from - it doesn't loop in my code.

**Comment by TheGr8** [comment]
I am not very strong in PHP, so there might be a better answer or more elegant ways to accomplish this but I was just able to make this work yesterday, so here goes...

You should be calling getProcessShipmentReply once for every package (which looks like you are already doing), after that, you should put something like this:

```
if(is_object($result->CompletedShipmentDetail->CompletedPackageDetails[0]))
{
	$pdfLabel = 'tmp/label-' . $item_seq . '.pdf';
	file_put_contents($pdfLabel, $result->CompletedShipmentDetail->CompletedPackageDetails[0]->Label->Parts[0]->Image);
	array_push($pdfLabels, $_SERVER['DOCUMENT_ROOT'] . '/' . $pdfLabel);
}
```
The reason I am pushing all PDF files into an array is to be able to iterrate through them for merging. So once you've generated all PDFs for individual packages you can merge them into a single PDF like this:

```
//Combine Labels:
$outputName = $_SERVER['DOCUMENT_ROOT'] . '/tmp/label.pdf';
$cmd = "gs -q -dNOPAUSE -dBATCH -sDEVICE=pdfwrite -sOutputFile=$outputName ";

foreach($pdfLabels as $file) {
    $cmd .= $file." ";
}
$result_merge = shell_exec($cmd);
```
And put this all the way at the top to declare lable file name array:
`$pdfLabels = array();
`

**Comment by mistris** [comment]
Do we really need to merge PDFs? I think that FedEx should send whole PDF in response.

**Comment by mistris** [comment]
I send this XML request to FedEx (I replaced the real values with dummy placeholders)
```
<SOAP-ENV:Envelope
	xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"
	xmlns:ns1="http://fedex.com/ws/ship/v12">
	<SOAP-ENV:Body>
		<ns1:ProcessShipmentRequest>
			<ns1:WebAuthenticationDetail>
				<ns1:UserCredential>
					<ns1:Key>KEY</ns1:Key>
					<ns1:Password>PASSWORD</ns1:Password>
				</ns1:UserCredential>
			</ns1:WebAuthenticationDetail>
			<ns1:ClientDetail>
				<ns1:AccountNumber>ACCOUNT_NUMBER</ns1:AccountNumber>
				<ns1:MeterNumber>METER_NUMBER</ns1:MeterNumber>
			</ns1:ClientDetail>
			<ns1:Version>
				<ns1:ServiceId>ship</ns1:ServiceId>
				<ns1:Major>12</ns1:Major>
				<ns1:Intermediate>1</ns1:Intermediate>
				<ns1:Minor>0</ns1:Minor>
			</ns1:Version>
			<ns1:RequestedShipment>
				<ns1:ShipTimestamp>2019-05-30T07:47:51+00:00</ns1:ShipTimestamp>
				<ns1:DropoffType>REGULAR_PICKUP</ns1:DropoffType>
				<ns1:ServiceType>INTERNATIONAL_ECONOMY</ns1:ServiceType>
				<ns1:PackagingType>YOUR_PACKAGING</ns1:PackagingType>
				<ns1:TotalWeight>
					<ns1:Units>KG</ns1:Units>
					<ns1:Value>1</ns1:Value>
				</ns1:TotalWeight>
				<ns1:Shipper>
					<ns1:AccountNumber>ACCOUNT_NUMBER</ns1:AccountNumber>
					<ns1:Contact>
						<ns1:PersonName>P_NAME</ns1:PersonName>
						<ns1:CompanyName>COMPANY_NAME</ns1:CompanyName>
						<ns1:PhoneNumber>PHONE_NUMBER</ns1:PhoneNumber>
						<ns1:EMailAddress>EMAIL_ADDRESS</ns1:EMailAddress>
					</ns1:Contact>
					<ns1:Address>
						<ns1:StreetLines>STREETLINE</ns1:StreetLines>
						<ns1:City>CITY</ns1:City>
						<ns1:PostalCode>POSTAL_CODE</ns1:PostalCode>
						<ns1:CountryCode>COUNTRY_CODE</ns1:CountryCode>
					</ns1:Address>
				</ns1:Shipper>
				<ns1:Recipient>
					<ns1:Contact>
						<ns1:PersonName>P_NAME</ns1:PersonName>
						<ns1:PhoneNumber>PHONE_NUMBER</ns1:PhoneNumber>
					</ns1:Contact>
					<ns1:Address>
						<ns1:StreetLines>ADDRESS_LINE</ns1:StreetLines>
						<ns1:City>CITY</ns1:City>
						<ns1:StateOrProvinceCode>STATE</ns1:StateOrProvinceCode>
						<ns1:PostalCode>POSTAL_CODE</ns1:PostalCode>
						<ns1:CountryCode>COUNTRY_CODE</ns1:CountryCode>
					</ns1:Address>
				</ns1:Recipient>
				<ns1:ShippingChargesPayment>
					<ns1:PaymentType>SENDER</ns1:PaymentType>
					<ns1:Payor>
						<ns1:ResponsibleParty>
							<ns1:AccountNumber>ACCOUNT_NUMBER</ns1:AccountNumber>
							<ns1:Contact>
								<ns1:PersonName>P_NAME</ns1:PersonName>
								<ns1:CompanyName>COMPANY_NAME</ns1:CompanyName>
								<ns1:PhoneNumber>PHONE_NUMBER</ns1:PhoneNumber>
								<ns1:EMailAddress>EMAIL_ADDRESS</ns1:EMailAddress>
							</ns1:Contact>
							<ns1:Address>
								<ns1:StreetLines>STREETLINE</ns1:StreetLines>
								<ns1:City>CITY</ns1:City>
								<ns1:PostalCode>POSTAL_CODE</ns1:PostalCode>
								<ns1:CountryCode>COUNTRY_CODE</ns1:CountryCode>
							</ns1:Address>
						</ns1:ResponsibleParty>
					</ns1:Payor>
				</ns1:ShippingChargesPayment>
				<ns1:CustomsClearanceDetail>
					<ns1:DutiesPayment>
						<ns1:PaymentType>SENDER</ns1:PaymentType>
						<ns1:Payor>
							<ns1:ResponsibleParty>
								<ns1:AccountNumber>ACCOUNT_NUMBER</ns1:AccountNumber>
								<ns1:Contact>
									<ns1:PersonName>P_NAME</ns1:PersonName>
									<ns1:CompanyName>COMPANY_NAME</ns1:CompanyName>
									<ns1:PhoneNumber>PHONE_NUMBER</ns1:PhoneNumber>
									<ns1:EMailAddress>EMAIL_ADDRESS</ns1:EMailAddress>
								</ns1:Contact>
								<ns1:Address>
									<ns1:StreetLines>STREETLINE</ns1:StreetLines>
									<ns1:City>CITY</ns1:City>
									<ns1:PostalCode>POSTAL_CODE</ns1:PostalCode>
									<ns1:CountryCode>COUNTRY_CODE</ns1:CountryCode>
								</ns1:Address>
							</ns1:ResponsibleParty>
						</ns1:Payor>
					</ns1:DutiesPayment>
					<ns1:CustomsValue>
						<ns1:Currency>USD</ns1:Currency>
						<ns1:Amount>289</ns1:Amount>
					</ns1:CustomsValue>
					<ns1:Commodities>
						<ns1:Name>TEST_NAME</ns1:Name>
						<ns1:NumberOfPieces>1</ns1:NumberOfPieces>
						<ns1:Description>TEST_DESCRIPTION</ns1:Description>
						<ns1:CountryOfManufacture>COUNTRY</ns1:CountryOfManufacture>
						<ns1:Weight>
							<ns1:Units>KG</ns1:Units>
							<ns1:Value>1.00</ns1:Value>
						</ns1:Weight>
						<ns1:Quantity>1</ns1:Quantity>
						<ns1:QuantityUnits>1</ns1:QuantityUnits>
						<ns1:UnitPrice>
							<ns1:Currency>USD</ns1:Currency>
							<ns1:Amount>289</ns1:Amount>
						</ns1:UnitPrice>
						<ns1:CustomsValue>
							<ns1:Currency>USD</ns1:Currency>
							<ns1:Amount>289</ns1:Amount>
						</ns1:CustomsValue>
					</ns1:Commodities>
				</ns1:CustomsClearanceDetail>
				<ns1:LabelSpecification>
					<ns1:LabelFormatType>COMMON2D</ns1:LabelFormatType>
					<ns1:ImageType>PDF</ns1:ImageType>
					<ns1:LabelStockType>PAPER_7X4.75</ns1:LabelStockType>
				</ns1:LabelSpecification>
				<ns1:RateRequestTypes>ACCOUNT</ns1:RateRequestTypes>
				<ns1:PackageCount>1</ns1:PackageCount>
				<ns1:RequestedPackageLineItems>
					<ns1:SequenceNumber>1</ns1:SequenceNumber>
					<ns1:Weight>
						<ns1:Units>KG</ns1:Units>
						<ns1:Value>1.00</ns1:Value>
					</ns1:Weight>
					<ns1:Dimensions>
						<ns1:Length>1</ns1:Length>
						<ns1:Width>1</ns1:Width>
						<ns1:Height>1</ns1:Height>
						<ns1:Units>CM</ns1:Units>
					</ns1:Dimensions>
					<ns1:ItemDescription>ITEM_DESCRIPTION</ns1:ItemDescription>
				</ns1:RequestedPackageLineItems>
			</ns1:RequestedShipment>
		</ns1:ProcessShipmentRequest>
	</SOAP-ENV:Body>
</SOAP-ENV:Envelope>
```

and in response I get PDF with 5 equal pages. The PDF should contain only 1 page because I try to ship only 1 item.
Can someone help me with this please?

**Comment by mistris** [comment]
@TheGr8 @JeremyDunn ping

**Comment by TheGr8** [comment]
I believe I saw in FedEx documentation that we receive a label back for each Ship request we make and we need to make separate requests for each package. So I figured we need to combine PDFs ourselves if we need to have a single one with all labels.
I don't know why you are getting 5 pages of the same label back, I always get one page PDFs back when I make requests.

**Comment by mistris** [comment]
@TheGr8 
1. Can you please give me an example of request XML (SOAP envelope) where you try to ship 1 item?
2. Can you please give me an example of request XML for MPS shipment?

**Comment by TheGr8** [comment]
@mistris I will gladly send you XML with SOAP envelopes if you tell me how to extract it from my calls. As I mentioned, I am not super strong in PHP, so I just tweaked the samples provided by Jeremy with his wrapper library.

**Comment by mistris** [comment]
@TheGr8 
```
$result = $request->getProcessShipmentReply($processShipmentRequest);
$soapClient = $request->getSoapClient();
$requestXML = $soapClient->__getLastRequest();
$responseXML = $soapClient->__getLastResponse();
```

**Comment by mistris** [comment]
@TheGr8 You said that you always get one page PDFs when you make requests.
Can you please share your PHP code where you use this library?

**Comment by mistris** [comment]
@TheGr8 Hi! :) Will you share your PHP code please where you ship 1 item?

**Comment by TheGr8** [comment]
I just emailed you the files for SOAP requests/responds and PHP code. I hope this helps.

**Comment by emmonuel** [comment]
Hi, about that question, there is a example like ship.php, but with multiple-package and "The package are the same" like this section in Fedex [https://imgur.com/a/OdAI4t2](url)
Thanks and regards.

**Comment by emmonuel** [comment]
`$requestedShipment->setTotalWeight(new ComplexType\Weight(array(
                    'Value' => 4,
                    'Units' => SimpleType\WeightUnits::_KG
        )));
        $requestedShipment->setMasterTrackingId(new ComplexType\TrackingId(array("TrackingIdType" => $oResultado->CompletedShipmentDetail->MasterTrackingId->TrackingIdType
                    , "FormId" => $oResultado->CompletedShipmentDetail->MasterTrackingId->FormId
                    , "TrackingNumber" => $oResultado->CompletedShipmentDetail->MasterTrackingId->TrackingNumber)));

        $requestedShipment->setRequestedPackageLineItems([
            $packageLineItem1
        ]);`

**Comment by emmonuel** [comment]
I think I found a solution, it's not pretty, but as where I work everything is "urgent", I end up doing it this way, and if they would require the PDFMerger library, because what you have to do when you request a guide of multiple packages, you will have to make the first request, save in a variable the result of the first request, and also save the PDF, in subsequent requests, you also have to generate and save the PDFs, so that PDFMerger takes all the generated files and compact them into a single file.
In the function that commented, is exactly the same as the example of ship.php, nothing else varies 2 things that vary in the first call of the function:
```
 $packageLineItem1 = new ComplexType\RequestedPackageLineItem();
        $packageLineItem1
                 //Set sequencenumber is now dynamic, depends of the number or packages
                ->setSequenceNumber($i)
                ->setItemDescription('Electronicos')
                ->setWeight(new ComplexType\Weight(array(
                            'Value' => 2,
                            'Units' => SimpleType\WeightUnits::_KG
        )));
```
```
$requestedShipment->setTotalWeight(new ComplexType\Weight(array(
                    'Value' => 4,
                    'Units' => SimpleType\WeightUnits::_KG
        )));
         //This is the new line, $oResultado is the variable saved in the first request
        $requestedShipment->setMasterTrackingId(new ComplexType\TrackingId(array("TrackingIdType" => $oResultado->CompletedShipmentDetail->MasterTrackingId->TrackingIdType
                    , "FormId" => $oResultado->CompletedShipmentDetail->MasterTrackingId->FormId
                    , "TrackingNumber" => $oResultado->CompletedShipmentDetail->MasterTrackingId->TrackingNumber)));

        $requestedShipment->setRequestedPackageLineItems([
            $packageLineItem1
        ]);
```
Having already saved all the pdfs generated depending on how many packages, with PDF merge, each call to the function, I will save it and merge them with PDFMerge
```
$pdf = new PDFMerger;
        //In the first call, i'm saving the file
        $pdf->addPDF($sArchivo, 'all');
        $arrArchivos[] = $sArchivo;
        for ($i = 2; $i <= $nGuias; $i++)
        {
             //This function returns the name of the generated PDF, but the function is the same as the first call, with the differences previously commented
            $sPDF = $this->multiplesPaquetes($result, $i, $nGuias);
            //I'll add this file to the final PDF merged
            $pdf->addPDF($sPDF, 'all');
            $arrArchivos[] = $sPDF;
        }
        //Merging all files in this file
        $pdf->merge('file', 'TEST4.pdf');
```
I hope you have understood me and someone will serve you this information, and an apology, English is not my native language
