### ISSUE TITLE
Shiping ServiceType Error

### ISSUE THREAD

**Issue by shivank44** [JeremyDunn/php-fedex-api-wrapper#110]
@JeremyDunn @TheGr8 @mistris @alexankit @lawkunchi
I generate label using ship service but when I change ShipType other than FEDEX_GROUND 
For Ex:-
**$requestedShipment->setServiceType(new SimpleType\ServiceType(SimpleType\ServiceType::_FEDEX_GROUND));**
TO
**$requestedShipment->setServiceType(new SimpleType\ServiceType(SimpleType\ServiceType::_INTERNATIONAL_ECONOMY));**

it shows below error

object(FedEx\ShipService\ComplexType\ProcessShipmentReply)#78 (2) {
  ["name":protected]=>
  string(20) "ProcessShipmentReply"
  ["values":protected]=>
  array(3) {
    ["HighestSeverity"]=>
    string(5) "ERROR"
    ["Notifications"]=>
    array(1) {
      [0]=>
      object(FedEx\ShipService\ComplexType\Notification)#92 (2) {
        ["name":protected]=>
        string(12) "Notification"
        ["values":protected]=>
        array(5) {
          ["Severity"]=>
          string(5) "ERROR"
          ["Source"]=>
          string(4) "ship"
          ["Code"]=>
          string(4) "2464"
          ["Message"]=>
          string(21) "Invalid service type."
          ["LocalizedMessage"]=>
          string(21) "Invalid service type."
        }
      }
    }
    ["Version"]=>
    object(FedEx\ShipService\ComplexType\VersionId)#100 (2) {
      ["name":protected]=>
      string(9) "VersionId"
      ["values":protected]=>
      array(4) {
        ["ServiceId"]=>
        string(4) "ship"
        ["Major"]=>
        int(12)
        ["Intermediate"]=>
        int(1)
        ["Minor"]=>
        int(0)
      }
    }
  }
}

How I can Change ShipService other than FEDEX_GROUND

**Comment by eclipxe13** [comment]
Honest question: why are you consuming ship version 12.1.0 ?, current is 23.0.0

I had similar issue (I don't have the full request/response right now) but because the service type required was not enabled on the services contracted with FedEx.
