### ISSUE TITLE
TrackReply not returning Events

### ISSUE THREAD

**Issue by joeybab3** [JeremyDunn/php-fedex-api-wrapper#111]
Let me know if I'm just completely going about this in the wrong way, but I'm using the TrackService to attempt to get the current status code to essentially confirm when a package has been picked up. 

According to [TrackReply Elements](https://www.fedex.com/us/developer/webhelp/ws/2018/US/index.htm#t=wsdvg%2FTrackReply_Elements.htm) somewhere in there should be Events (Events/EventType seems to be what I'm after), but at least using the example provided, only `CompletedTrackDetails` are returned.

**Comment by joeybab3** [comment]
I was just going about this incorrectly and needed to pass TrackRequestProcessingOptionType.

**Comment by govindtotla** [comment]
any way to include TrackingDateOrTimestampType (ESTIMATED_DELIVERY), I need to find the shipping promised date from fedex.
