### ISSUE TITLE
ship for international issue

### ISSUE THREAD

**Issue by codercodercodercoder** [JeremyDunn/php-fedex-api-wrapper#113]
If both the recipient and sender are in the United States, they work well. But if the recipient is in Canada, there is a problem.

irst I change serviceType to INTERNATIONAL_PRIORITY，then I get a error,the code is 2033 and the message is Customs Value is required.

So I add this code:
`
$money = new ComplexType\Money();
$money->setCurrency('USD');
$money->setAmount('120');
$cus = new ComplexType\CustomsClearanceDetail();
$cus->setCustomsValue($money);
$requestedShipment->setCustomsClearanceDetail($cus);
`
Then I get two errors.First error code is 6005,message is Commodities are required.Second error code is 2009, message is Duties payment type is not compatible with destination country.

I added some more code:
`
$payor = new ComplexType\Payor();

$payor->setResponsibleParty($recipient);

$pay  = new ComplexType\Payment();

$pay->setPaymentType(SimpleType\PaymentType::_SENDER);

$pay->setPayor($payor);

$arr = array('name'=>'test','NumberOfPieces'=>5,'Description'=>'tetetetetetetet','CountryOfManufacture'=>'CN','HarmonizedCode'=>'851711100000','weight'=>array('Value' => 10,'Units' => SimpleType\WeightUnits::_LB),'Quantity'=>1,'QuantityUnits'=>'PCS');

$cus->setCustomsValue($money);

$cus->setDutiesPayment($pay);
` 

But still not right,I get a new error that 'SOAP-ERROR: Encoding: object has no 'Weight' property'.

Can you help me out? Thank you very much!

**Comment by mswaqas** [comment]
I'm also facing the same issue.
![Capture](https://user-images.githubusercontent.com/31316860/87222829-670b8c00-c388-11ea-80cb-5bced4fe0214.PNG)

**Comment by nikunjsilvercayde** [comment]
I am also getting below error..
[HighestSeverity] => ERROR
            [Notifications] => Array
                (
                    [0] => FedEx\ShipService\ComplexType\Notification Object
                        (
                            [name:protected] => Notification
                            [values:protected] => Array
                                (
                                    [Severity] => ERROR
                                    [Source] => ship
                                    [Code] => 6065
                                    [Message] => Commodities are required
                                    [LocalizedMessage] => Commodities are required
                                )

                        )

                )

**Comment by lizeshakya** [comment]
Any solutions found? I am struck with the same problem

**Comment by lizeshakya** [comment]
Thank you for helping out @codercodercodercoder 

> But still not right,I get a new error that 'SOAP-ERROR: Encoding: object has no 'Weight' property'.
> 
> Can you help me out? Thank you very much!

You might need to provide the Weight Class in the requestedPackageLink. I did similar like:


```
$requestedPackageLineItem->Dimensions->Length = 0;
$requestedPackageLineItem->Dimensions->Units = SimpleType\LinearUnits::_IN;
$requestedPackageLineItem->Weight->Value = 151;
$requestedPackageLineItem->Weight->Units = SimpleType\WeightUnits::_LB;
$requestedPackageLineItem->setCustomerReferences([$refCust, $refDept, $refPO]);
$requestedPackageLineItems[] = $requestedPackageLineItem;
```
