### ISSUE TITLE
How to send rate request of specific shipment type?

### ISSUE THREAD

**Issue by nikunjsilvercayde** [JeremyDunn/php-fedex-api-wrapper#114]
We want to get rate request for specific service type like "FEDEX GROUND" or other. 
Please advise.

**Comment by jigneshradicalloop** [comment]
check https://github.com/JeremyDunn/php-fedex-api-wrapper/blob/master/examples/rate-request.php

**Comment by nikunjsilvercayde** [comment]
$rateRequest->RequestedShipment->ServiceType = SimpleType\ServiceType::_FEDEX_2_DAY;
	$rateRequest->RequestedShipment->PackagingType = "FEDEX_SMALL_BOX";
	
$rateRequest->RequestedShipment->RateRequestTypes = [SimpleType\RateRequestType::_PREFERRED, SimpleType\RateRequestType::_LIST];
