### ISSUE TITLE
How can i set PurposeOfShipmentType in rate-request?

### ISSUE THREAD

**Issue by atwebify** [JeremyDunn/php-fedex-api-wrapper#117]
Hi, 
I want to set set PurposeOfShipmentType to sold for rate-request and unable succeed...

**Comment by skyviewmedia** [comment]
any luck with this ?? Facing the same issue.
Shipments within India require this value.

I tried 
$rateRequest->CustomsClearanceDetail->CommercialInvoice->Purpose = SimpleType\PurposeOfShipmentType::_SOLD;

but doesn't work.

**Comment by atwebify** [comment]
$rateRequest->RequestedShipment->CustomsClearanceDetail->CommercialInvoice->Purpose =  SimpleType\PurposeOfShipmentType::_SOLD;

**Comment by skyviewmedia** [comment]
Hey, thanks ! That did resolve the issue with PurposeOfShipmentType.
Now stuck with "There are no valid services available. " 
Not sure why that would pop up.
Its using a production key.

**Comment by atwebify** [comment]
Check serviceable  area of fedex
