### ISSUE TITLE
upload-documents.php example issue

### ISSUE THREAD

**Issue by jakovec** [JeremyDunn/php-fedex-api-wrapper#120]
When setting DocumentContent on UploadDocumentsRequest() there is no need (orherwise FedEx will receive damaged document content) to base64_encode the file content as it is encoded somewhere else in the code (or on FedEx request reception).

Not sure where this happens but after comparing requests log with FedEx specialist on the phone we've found out that only NOT base64 encoded documentContent in my script will be decoded fine on FedEx side.

**Comment by JeremyDunn** [comment]
@jakovec Please submit a pull request for the fix you described.

**Comment by Destronom** [comment]
@jakovec I also had the same problem, in the examples there is no need to base64_encode the file content
