### ISSUE TITLE
Fedex Ground Home Delivery Example

### ISSUE THREAD

**Issue by nikunjsilvercayde** [JeremyDunn/php-fedex-api-wrapper#121]
Hello

I am trying to get Rate or Create Label in Fedex Ground Home Delivery options but it's showing me error of (Service type Ground Home Delivery must be designated as residential delivery.)

Can anyone please give me example of home delivery for where to pass this data?

**Comment by nbokkisam** [comment]
I am facing similar issue. Were you able to resolve? Thank You

**Comment by nikjoshi96** [comment]
HI,
Yes I got the answer for get and Create Label of Ground Home Delivery.

Here below is the examples.

**For Rate Request..**
if($address_type != '' && $address_type == 'RESIDENTIAL' && $service_type == 'GROUND_HOME_DELIVERY') {
			$rateRequest->RequestedShipment->Recipient->Address->Residential = TRUE;
		}
**For Create Label**
$recipientAddress = new \FedEx\ShipService\ComplexType\Address();
        $recipientAddress
        ->setStreetLines([$address_street])
        ->setCity($address_city)
        ->setStateOrProvinceCode($address_region)
        ->setPostalCode($address_zipcode)
        ->setCountryCode($address_contry);

        if($address_type != '' && $address_type == 'RESIDENTIAL')
        {
            $recipientAddress->setResidential(TRUE);
        }
