### ISSUE TITLE
FedEx Warning: The returned rate types are in the requested preferred currency; preferred rates not returned.

### ISSUE THREAD

**Issue by isadma** [JeremyDunn/php-fedex-api-wrapper#125]
When I want to get rates from FedEx, I am getting this warning.

```
"Severity" => "WARNING"
"Source" => "crs"
"Code" => "396"
"Message" => "The returned rate types are in the requested preferred currency; preferred rates not returned."
"LocalizedMessage" => "The returned rate types are in the requested preferred currency; preferred rates not returned."

```
Controller:

```
$rateRequest->RequestedShipment->ShippingChargesPayment->PaymentType = PaymentType::_SENDER;
$rateRequest->RequestedShipment->PreferredCurrency = 'USD';
$rateRequest->RequestedShipment->RateRequestTypes = [RateRequestType::_PREFERRED, RateRequestType::_LIST];
```

**Comment by thelar** [comment]
Hi @isadma did you ever find out why this was? I'm having the same issue, a 396 warning telling me that preferred rates are not being returned.

My controller code:

`
$rateRequest->RequestedShipment->PreferredCurrency = get_woocommerce_currency();
//shipping charges payment
        $rateRequest->RequestedShipment->ShippingChargesPayment->PaymentType = SimpleType\PaymentType::_SENDER;

//rate request types
        $rateRequest->RequestedShipment->RateRequestTypes = [SimpleType\RateRequestType::_PREFERRED, SimpleType\RateRequestType::_LIST];
`

**Comment by syssam** [comment]
face the same issue, any solutions?

**Comment by JerryLosey** [comment]
Add another to the pile. I'm seeing the same issue.
```"HighestSeverity":"WARNING",
   "Notifications":{
      "Severity":"WARNING",
      "Source":"crs",
      "Code":"396",
      "Message":"The returned rate types are in the requested preferred currency; preferred rates not returned.",
      "LocalizedMessage":"The returned rate types are in the requested preferred currency; preferred rates not returned."
   },

**Comment by mufi-siebird** [comment]
Anyone sorted out this issue?its been 2 years and no answer at all..

**Comment by dijitalbrains-dev** [comment]
just a workaround 

you can change the preferred_currency to the country the product is being shipped.

like if the package is being deliverd to Australia then pass the currency AUD in the request then it does include the preferred rates and also the conversion rate and then you can convert back to USD after the response

by doing this I get this in the response. as you can see the exchange rate is available and you can convert back to USD

`"ShipmentRateDetail": {
                            "RateType": "PREFERRED_ACCOUNT_SHIPMENT",
                            "RateScale": "US001OFJ_03_YOUR_PACKAGING",
                            "RateZone": "US001O",
                            "RatedWeightMethod": "ACTUAL",
                            "CurrencyExchangeRate": {
                                "FromCurrency": "USD",
                                "IntoCurrency": "AUD",
                                "Rate": "1.53"
                            },
                            "DimDivisor": 166,
                            "DimDivisorType": "PRODUCT",
                            "FuelSurchargePercent": "21.0",
                            "TotalBillingWeight": {
                                "Units": "LB",
                                "Value": "15.0"
                            },
                            "TotalBaseCharge": {
                                "Currency": "AUD",
                                "Amount": "713.23"
                            },
                            "TotalFreightDiscounts": {
                                "Currency": "AUD",
                                "Amount": "611.96"
                            },
                            "TotalNetFreight": {
                                "Currency": "AUD",
                                "Amount": "101.27"
                            },
                            "TotalSurcharges": {
                                "Currency": "AUD",
                                "Amount": "25.26"
                            },
                            "TotalNetFedExCharge": {
                                "Currency": "AUD",
                                "Amount": "126.53"
                            },
                            "TotalTaxes": {
                                "Currency": "AUD",
                                "Amount": "0.0"
                            },
                            "TotalNetCharge": {
                                "Currency": "AUD",
                                "Amount": "126.53"
                            },
                            "TotalRebates": {
                                "Currency": "AUD",
                                "Amount": "0.0"
                            },
                            "TotalDutiesAndTaxes": {
                                "Currency": "AUD",
                                "Amount": "0.0"
                            },
                            "TotalAncillaryFeesAndTaxes": {
                                "Currency": "AUD",
                                "Amount": "0.0"
                            },
                            "TotalDutiesTaxesAndFees": {
                                "Currency": "AUD",
                                "Amount": "0.0"
                            },
                            "TotalNetChargeWithDutiesAndTaxes": {
                                "Currency": "AUD",
                                "Amount": "126.53"
                            },
                            "FreightDiscounts": {
                                "RateDiscountType": "VOLUME",
                                "Description": "Volume",
                                "Amount": {
                                    "Currency": "AUD",
                                    "Amount": "611.96"
                                },
                                "Percent": "85.8"
                            },
                            "Surcharges": [
                                {
                                    "SurchargeType": "INSURED_VALUE",
                                    "Description": "Insured value",
                                    "Amount": {
                                        "Currency": "AUD",
                                        "Amount": "3.99"
                                    }
                                },
                                {
                                    "SurchargeType": "OTHER",
                                    "Description": "Demand Surcharge",
                                    "Amount": {
                                        "Currency": "AUD",
                                        "Amount": "0.0"
                                    }
                                },
                                {
                                    "SurchargeType": "FUEL",
                                    "Description": "Fuel",
                                    "Amount": {
                                        "Currency": "AUD",
                                        "Amount": "21.27"
                                    }
                                }
                            ]
                        }
                    },`

**Comment by m-faizanrasool** [comment]
just a workaround 

you can change the preferred_currency to the country the product is being shipped.

like if the package is being deliverd to Australia then pass the currency AUD in the preferred_currency and USD as the currency of the amount of the package or commodities or insured value. then it does include the preferred rates and also the conversion rate and then you can convert back to USD after the response

by doing this I get this in the response. as you can see the exchange rate is available and you can convert back to USD

> "ShipmentRateDetail": {
                            "RateType": "PREFERRED_ACCOUNT_SHIPMENT",
                            "RateScale": "US001OFJ_03_YOUR_PACKAGING",
                            "RateZone": "US001O",
                            "RatedWeightMethod": "ACTUAL",
                            "CurrencyExchangeRate": {
                                "FromCurrency": "USD",
                                "IntoCurrency": "AUD",
                                "Rate": "1.53"
                            },
                            "DimDivisor": 166,
                            "DimDivisorType": "PRODUCT",
                            "FuelSurchargePercent": "21.0",
                            "TotalBillingWeight": {
                                "Units": "LB",
                                "Value": "15.0"
                            },
                            "TotalBaseCharge": {
                                "Currency": "AUD",
                                "Amount": "713.23"
                            },
                            "TotalFreightDiscounts": {
                                "Currency": "AUD",
                                "Amount": "611.96"
                            },
                            "TotalNetFreight": {
                                "Currency": "AUD",
                                "Amount": "101.27"
                            },
                            "TotalSurcharges": {
                                "Currency": "AUD",
                                "Amount": "25.26"
                            },
                            "TotalNetFedExCharge": {
                                "Currency": "AUD",
                                "Amount": "126.53"
                            },
                            "TotalTaxes": {
                                "Currency": "AUD",
                                "Amount": "0.0"
                            },
                            "TotalNetCharge": {
                                "Currency": "AUD",
                                "Amount": "126.53"
                            },
                            "TotalRebates": {
                                "Currency": "AUD",
                                "Amount": "0.0"
                            },
                            "TotalDutiesAndTaxes": {
                                "Currency": "AUD",
                                "Amount": "0.0"
                            },
                            "TotalAncillaryFeesAndTaxes": {
                                "Currency": "AUD",
                                "Amount": "0.0"
                            },
                            "TotalDutiesTaxesAndFees": {
                                "Currency": "AUD",
                                "Amount": "0.0"
                            },
                            "TotalNetChargeWithDutiesAndTaxes": {
                                "Currency": "AUD",
                                "Amount": "126.53"
                            },
                            "FreightDiscounts": {
                                "RateDiscountType": "VOLUME",
                                "Description": "Volume",
                                "Amount": {
                                    "Currency": "AUD",
                                    "Amount": "611.96"
                                },
                                "Percent": "85.8"
                            },
                            "Surcharges": [
                                {
                                    "SurchargeType": "INSURED_VALUE",
                                    "Description": "Insured value",
                                    "Amount": {
                                        "Currency": "AUD",
                                        "Amount": "3.99"
                                    }
                                },
                                {
                                    "SurchargeType": "OTHER",
                                    "Description": "Demand Surcharge",
                                    "Amount": {
                                        "Currency": "AUD",
                                        "Amount": "0.0"
                                    }
                                },
                                {
                                    "SurchargeType": "FUEL",
                                    "Description": "Fuel",
                                    "Amount": {
                                        "Currency": "AUD",
                                        "Amount": "21.27"
                                    }
                                }
                            ]
                        }
                    },
