### ISSUE TITLE
Rate Requesting and Tracking Shows SoapFault Internal Server Error

### ISSUE THREAD

**Issue by lYesterdaYl** [JeremyDunn/php-fedex-api-wrapper#127]
There was no error yesterday. Changed nothing. This error shows up since today.

![image](https://user-images.githubusercontent.com/5135163/71935508-ce3b5000-315b-11ea-9609-776646583256.png)

**Comment by rodrigokestler** [comment]
Same here. No error yesterday, today the Soap Fault Internal Server is displayed using FedEx\TrackService\Request to track an ID.
https://flareapp.io/share/omwGVGmE

**Comment by lYesterdaYl** [comment]
> Same here. No error yesterday, today the Soap Fault Internal Server is displayed using FedEx\TrackService\Request to track an ID.
> https://flareapp.io/share/omwGVGmE

I think creating label is working for me, but tracking and request rate are not working so far.

**Comment by eliza2** [comment]
Fatal error: Uncaught SoapFault exception: [HTTP] Internal Server Error in D:\Server\htdocs\fed5\vendor\jeremy-dunn\php-fedex-api-wrapper\src\FedEx\RateService\Request.php:29 Stack trace: #0 [internal function]: SoapClient->__doRequest('<?xml version="...', 'https://wsbeta....', 'http://fedex.co...', 1, 0) #1 D:\Server\htdocs\fed5\vendor\jeremy-dunn\php-fedex-api-wrapper\src\FedEx\RateService\Request.php(29): SoapClient->__call('getRates', Array) #2 D:\Server\htdocs\fed5\rate-request.php(80): FedEx\RateService\Request->getGetRatesReply(Object(FedEx\RateService\ComplexType\RateRequest)) #3 {main} thrown in D:\Server\htdocs\fed5\vendor\jeremy-dunn\php-fedex-api-wrapper\src\FedEx\RateService\Request.php on line 29


facing same issue  , it was working fine but today i got error.

**Comment by kreitje** [comment]
They are doing some maintenance today and maybe jumped the gun?

https://www.fedex.com/en-us/developer/announcements.html

**Comment by tylerwood** [comment]
I had the same issues yesterday all afternoon and evening. This morning it is working intermittently. From the announcement it may be mostly down from 9-5 today, then intermittent for the next week-and-a-half

**Comment by mijaelsaban** [comment]
Hi, After certain requests I am getting
Could not connect to host [internal function]: SoapClient->__doRequest()

I disabled Soap cache in my php.ini but still the same

Anyone same issue?
