### ISSUE TITLE
 I can't use the tracking service.

### ISSUE THREAD

**Issue by rvmartins** [JeremyDunn/php-fedex-api-wrapper#128]
Does this API still work?
How to switch to production mode?
I just want to use the tracking service. 
If I put the production data in the credentials.php file, there is an error in the return.

**Comment by tylerwood** [comment]
to switch to using the production mode, uncomment this line in your code, so that you're using the production endpoint 'ws.fedex.com' instead of 'wsbeta.fedex.com': 

//$rateServiceRequest->getSoapClient()->__setLocation(Request::PRODUCTION_URL); //use production URL

**Comment by rvmartins** [comment]
Thanks.
