### ISSUE TITLE
Is It Possible To Unify Duplicate Classes?

### ISSUE THREAD

**Issue by MannikJ** [JeremyDunn/php-fedex-api-wrapper#132]
There are a lot of classes that are exactly the same but reside in different namespaces, because they belong to different sub services.

However, in the example implementation it looks that this has once been different, since types like PaymentType or RateRequest type are not imported from namespaces prefixed with the sub service. 

So would it be possible to avoid this kind of duplication in a future release?

**Comment by e-hop** [comment]
+1
