### ISSUE TITLE
Switch from Testing to Production

### ISSUE THREAD

**Issue by dspeer** [JeremyDunn/php-fedex-api-wrapper#133]
Hello!
I have everything working, and now I am making the switch to Production environment. I am doing this by setting the URI in 'TESTING' to the same as in PRODUCTION and changing the credentials file. But that can't be the solution. Is there a way to do this by changing one setting? I figured this out for shipment request but not for address validation

**Comment by MichaelOlatunji** [comment]
I have the same question as well

**Comment by iMezied** [comment]
I tried this as mentioned in the example and the same result, fail with an authentication 
after tracking the request I fount the get rate service use shipment endpoint in production
I solved this by set the production URL as a string as below 
`$rateServiceRequest->getSoapClient()->__setLocation('https://ws.fedex.com:443/web-services/rate');`

I hope this useful
