### ISSUE TITLE
Is this the official Fedex source Code?

### ISSUE THREAD

**Issue by EinSoldiatGott** [JeremyDunn/php-fedex-api-wrapper#134]
Hi, I'm very confused I just downloaded the PHP code from fedex Dev WebPage with documentation and the I found your code.

I searched from some of the Fedex files here in your code and I was unable to find them. 

So i was wondering if this has been a 3yr development independent of the Fedex original code? 

Thanks

**Comment by TheGr8** [comment]
This is not an official FedEx repo. FedEx source you are referring to is just examples of how to utilize their Web Services. 
This is a 3rd party repo of a PHP wrapper, which simplifies working with raw XML messages while constructing the requests and parsing the responses.

**Comment by EinSoldiatGott** [comment]
Thank you very much for the explanation and your response :D
