### ISSUE TITLE
How to make LTL Rate Requests? Any Example?

### ISSUE THREAD

**Issue by awais300** [JeremyDunn/php-fedex-api-wrapper#135]

**Comment by SannketPatel** [comment]
I have same question. I asked in support emails. But nobody is responding there. 
Please Freight API support person, Can you help to get FREIGHT SERVICE (LTL) rates ? 
Example code always response back as "There are no valid Freight services available."  

I am able to ret rates for couriers/parcels. Facing problem to get LTL rates. 
Thanks in advance.

**Comment by era404design** [comment]
I'm also looking for an example showing how to use this library to request LTL Freight quotes.
Specifically LTL VAN and LTL FLAT BED.
Any help would be appreciated. Thanks all.
