### ISSUE TITLE
Error on create shipment example

### ISSUE THREAD

**Issue by imykie** [JeremyDunn/php-fedex-api-wrapper#137]
when I was trying to use the wrapper folloing the example at 
https://github.com/JeremyDunn/php-fedex-api-wrapper/blob/master/examples/ship.php

returns error:

Fatal error: Uncaught SoapFault exception: [Client] SOAP-ERROR: Encoding: Element 'Major' has fixed value '23' (value '21' is not allowed) in C:\xampp\htdocs\myprojectname\vendor\jeremy-dunn\php-fedex-api-wrapper\src\FedEx\ShipService\Request.php:48 Stack trace: #0 C:\xampp\htdocs\sell-your-dinar\dinar-db\vendor\jeremy-dunn\php-fedex-api-wrapper\src\FedEx\ShipService\Request.php(48): SoapClient->__call('processShipment', Array) #1 C:\xampp\htdocs\myprojectname\src\api\label.php(132): FedEx\ShipService\Request->getProcessShipmentReply(Object(FedEx\ShipService\ComplexType\ProcessShipmentRequest)) #2 {main} thrown in C:\xampp\htdocs\sell-your-dinar\dinar-db\vendor\jeremy-dunn\php-fedex-api-wrapper\src\FedEx\ShipService\Request.php on line 48

**Comment by pcualmac** [comment]
line 29 to 30
write
$version
    ->setMajor(24)
    ->setIntermediate(0)
    ->setMinor(0)
    ->setServiceId('ship');

**Comment by MichaelOlatunji** [comment]
Thank you, It worked

Also, I want to how to convert the response to a more readable type and to the form that can be use in what I'm buiding

**Comment by pcualmac** [comment]
Me to this lib need a documentation.
