### ISSUE TITLE
Vendor folder missing 

### ISSUE THREAD

**Issue by tpt-prasy** [JeremyDunn/php-fedex-api-wrapper#14]
Found that vendor folder and autoload.php is missing. Where can I download?

**Comment by DS-Matt** [comment]
These come from composer - not a specific package.  You should close this issue as they have nothing to do with this package/library. 

https://getcomposer.org/doc/01-basic-usage.md#autoloading

**Comment by tpt-prasy** [comment]
Sorry about the delay. Just noticed. Hope it is closed now.
