### ISSUE TITLE
Help with special service paremeters (e.g. Saturday Delivery)

### ISSUE THREAD

**Issue by NBlanchette** [JeremyDunn/php-fedex-api-wrapper#146]
Trying to get a rate on a box to be delivered on a Saturday.

Here's the relevant code (that differs from the rate example):
`$rateRequest->RequestedShipment->SpecialServicesRequested = [SimpleType\ServiceOptionType::_SATURDAY_DELIVERY];`

returns the following error

`TypeError: Argument 1 passed to FedEx\RateService\ComplexType\RequestedShipment::setSpecialServicesRequested() must be an instance of FedEx\RateService\ComplexType\ShipmentSpecialServicesRequested, array given`

I'm sure I'm missing something obvious here - but am not seeing it.

**Comment by TheGr8** [comment]
Instead of:
`  $requestedShipment->SpecialServicesRequested = [SimpleType\ServiceOptionType::_SATURDAY_DELIVERY];`
Try this:
`  $requestedShipment->SpecialServicesRequested->SpecialServiceTypes = [SimpleType\ServiceOptionType::_SATURDAY_DELIVERY];`

**Comment by NBlanchette** [comment]
Ahhh there we go, thank you so much @TheGr8 !
