### ISSUE TITLE
How can I create international shipment?

### ISSUE THREAD

**Issue by nikunjsilvercayde** [JeremyDunn/php-fedex-api-wrapper#152]
I want to create international shipping label and It needs Customs Documents and values.. How can i upload customs document and customs values? I need one example of international shipment create. Thanks

**Comment by pcualmac** [comment]
@nikunjsilvercayde

me to.

**Comment by brookfitzer** [comment]
> I want to create international shipping label and It needs Customs Documents and values.. How can i upload customs document and customs values? I need one example of international shipment create. Thanks

Hello, are you using fedex.com?  You can use the FedEx-generated Commercial Invoice based on the Commodity info from box #6 in the below snippy, or upload your own where I highlighted in box #7...

Let me know if you are using a different shipping platform, and I can try to help there as well.

![Screenshot fedex intl shipment](https://user-images.githubusercontent.com/79641092/113329017-45698080-92da-11eb-9a03-fb579932c4a1.JPG)

**Comment by brookfitzer** [comment]
@JeremyDunn have you set up many Estimated Duty/Tax API's for US Export (Intl) shipments via FedEx Web Services?  

You likely know already, but it takes special permission beyond the FedEx Developer Resource Center to access the live data... as well as further mapping for commodity codes/country of mfg/value/etc.

Thanks for any thoughts, I'd really like to find a live example and 1) how much integration labor/costs involved, and 2) how smoothly/quickly it  makes calls for different shopping carts. 

Take good care!

**Comment by JeremyDunn** [comment]
@brookfitzer Sorry, I've never done this before.

**Comment by brookfitzer** [comment]
Oh, Kk. Thx!
