### ISSUE TITLE
How can create  Multiple-Package Shipping Label Shipments

### ISSUE THREAD

**Issue by taleemhussain** [JeremyDunn/php-fedex-api-wrapper#154]
@JeremyDunn @shrimpwagon 
I am using the below API to get a shipping label. how I create multiple Package shipping label using the below API
https://github.com/JeremyDunn/php-fedex-api-wrapper/blob/master/examples/ship.php

I want to help how I can pass the master tracking id to create a 2nd package label.
have a look screenshot: https://i.imgur.com/KFftzPh.png

**Comment by nikunjsilvercayde** [comment]
[check_ship_label_mutlipackage.txt](https://github.com/JeremyDunn/php-fedex-api-wrapper/files/5238489/check_ship_label_mutlipackage.txt)

Please check this example for creating multiple package tracking code..

**Comment by eduardo069** [comment]
@nikunjsilvercayde Use your code and it gave me this error in the first packet
`Invalid shipment totalWeight`
You have not been presented with this error
