### ISSUE TITLE
PHP 8 Compatibility?

### ISSUE THREAD

**Issue by GenericHero01** [JeremyDunn/php-fedex-api-wrapper#164]
Howdy!

This looks like a great package for an upcoming project, however, I ran into some compatibility/deprecation issues when attempting a RateQuote.

`ErrorException
Method ReflectionParameter::getClass() is deprecated`

Line 72 of AbstracComplexType.php is the culprit, though that's also used later down the file:

`$parameterClass = $reflectionClass->getMethod($setterMethodName)->getParameters()[0]->getClass();`

I can suppress error messages on my end and get it working, however, that doesn't feel great.  Are there any plans to refactor for PHP 8 support?  I'm poking at it on my end as well, though I'll be the first to admit I'm a relative PHP newbie.

Thanks!

**Comment by JeremyDunn** [comment]
These deprecated warning should be fixed now in version 5.0.1.

**Comment by GenericHero01** [comment]
Excellent, I just updated and see no errors.  Thanks!
