### ISSUE TITLE
request help for link ship to upload-documents

### ISSUE THREAD

**Issue by pcualmac** [JeremyDunn/php-fedex-api-wrapper#166]
Dear all,

I am sorry for this request but I try to understand how link my Invoice to the schipping.

I have look inside schip example and  upload-documents example but i can't find the link.

Do i need have create ship first and pass a ref to the upload-documents or  upload-documents first and ship after?

Please any help?

@JeremyDunn JeremyDunn

**Comment by mookie44** [comment]
Hello

This the code I used to upload images and docs to the account.
You then use whatever ID you set for the documents in future calls to the API.

`$UploadImagesRequest = new \FedEx\UploadDocumentService\ComplexType\UploadImagesRequest();
        //auth
        $userCredential = new \FedEx\UploadDocumentService\ComplexType\WebAuthenticationCredential();
        $userCredential
            ->setKey($this->FEDEX_LIVE_KEY)
            ->setPassword($this->FEDEX_LIVE_PASSWORD);

        $webAuthenticationDetail = new \FedEx\UploadDocumentService\ComplexType\WebAuthenticationDetail();
        $webAuthenticationDetail->setUserCredential($userCredential);
        // client
        $clientDetail = new \FedEx\UploadDocumentService\ComplexType\ClientDetail();
        $clientDetail
            ->setAccountNumber($this->FEDEX_LIVE_ACCOUNT_NUMBER)
            ->setMeterNumber($this->FEDEX_LIVE_METER_NUMBER);
        // version
        $version = new \FedEx\UploadDocumentService\ComplexType\VersionId();
        $version
            ->setMajor(11)
            ->setIntermediate(0)
            ->setMinor(0)
            ->setServiceId('cdus');
        //web authentication detail
        $UploadImagesRequest->setWebAuthenticationDetail($webAuthenticationDetail);
        $UploadImagesRequest->setClientDetail($clientDetail);
        $UploadImagesRequest->setVersion($version);
        //
        $image = base64_encode(file_get_contents('/var/www/webroot/fedex_signature.png'));
        $UploadImagesRequest->setImages(['Id'=>'IMAGE_2','Image'=>$image]);
        debug($UploadImagesRequest);
        //
        $request = new \FedEx\UploadDocumentService\Request();
        
        $request->getSoapClient()->__setLocation('https://ws.fedex.com:443/web-services/uploaddocument');
        debug($request);
        try {
            $UploadImagesReply = $request->getUploadImagesReply($UploadImagesRequest);
            //debug($UploadImagesReply->getSoapClient()->__getLastRequest());
            //debug($UploadImagesReply->getSoapClient()->__getLastResponse());
            debug($UploadImagesReply);
        } catch (\Exception $e) {
            debug($e);
        }`
