### ISSUE TITLE
$reflectionNamedType in AbstractComplexType can be null

### ISSUE THREAD

**Issue by TomAshe** [JeremyDunn/php-fedex-api-wrapper#168]
In this block in AbstractComplexType:

```
        $setterMethodName = "set{$name}";
        $reflectionClass = new ReflectionClass($this);
        if ($reflectionClass->hasMethod($setterMethodName)) {
            $reflectionNamedType = $reflectionClass->getMethod($setterMethodName)->getParameters()[0]->getType();
            /* @var $reflectionNamedType ReflectionNamedType */
            $parameterClassName = $reflectionNamedType->getName();

            if (class_exists($parameterClassName)) {
                $this->$setterMethodName(new $parameterClassName);
                return $this->values[$name];
            }
        }

```

The variable `$reflectionNamedType` will be null if the parameter doesn't have an explicit type set, e.g. for the property setter: `public function setCode($code)`.

This throws an uncaught error.

Seems either all the setters need to have the type set for their parameters, e.g. `public function setCode(string $code)` or else a check should be made to see if `$reflectionNamedType` is not null before calling `->getName()` on it.

**Comment by TomAshe** [comment]
I've submitted Pull Request #169 to address this issue.

**Comment by ajnieset** [comment]
+1 for this issue to be resolved. Would like to upgrade to php 8 but this is a breaking bug for my application

**Comment by Soetens** [comment]
Also got into this problem after an update to php8
