### ISSUE TITLE
UploadDocumentService error

### ISSUE THREAD

**Issue by pcualmac** [JeremyDunn/php-fedex-api-wrapper#171]
Dear all,

Sorry for my question but I am stack.

I try to run [upload-documents](https://github.com/JeremyDunn/php-fedex-api-wrapper/blob/master/examples/upload-documents.php) but i get this error.

```php
FedEx\UploadDocumentService\ComplexType\UploadDocumentsReply^ {#1876
 #name: "UploadDocumentsReply"
  #values: array:3 [
    "HighestSeverity" => "ERROR"
    "Notifications" => array:1 [
      0 => FedEx\UploadDocumentService\ComplexType\Notification^ {#2024
        #name: "Notification"
        #values: array:4 [
          "Severity" => "ERROR"
          "Source" => "prof"
          "Code" => "1000"
          "Message" => "Authentication Failed"
        ]
      }
    ]
    "Version" => FedEx\UploadDocumentService\ComplexType\VersionId^ {#2025
      #name: "VersionId"
      #values: array:4 [
        "ServiceId" => "cdus"
        "Major" => 17
        "Intermediate" => 0
        "Minor" => 0
      ]
    }
  ]
}
```
I am secure of my credential and I use my test credential.

Do not consider  "Major" => 17 I have update from  "Major" => 11 also when I was use
the second i still have same error.
Plese help.

@JeremyDunn @colinodell  @umpirsky  @stef686

**Comment by colinodell** [comment]
@pcualmac Unfortunately I no longer use this library and I haven't worked with the Upload Document service before, so I might not be much help here.  My best guess is that either the credentials are incorrect or perhaps your account isn't authorized to use that service; in either case, I would recommend you contact FedEx Web Services Support for assistance, as they'll be best able to tell you why their API is saying your authentication failed.

**Comment by pcualmac** [comment]
@colinodell 
Thanks colinodell.
Sorry for border you

**Comment by lizeshakya** [comment]
Did you find the solution @pcualmac ? I am also struck in the same problem.
