### ISSUE TITLE
examples/ship.php -> "Action type TRANSFER is not allowed for this request."

### ISSUE THREAD

**Issue by dakhnod** [JeremyDunn/php-fedex-api-wrapper#18]
when running examples/ship.php with all credentials filled in i get the following error:

object(stdClass)#29 (3) {
  ["HighestSeverity"]=>
  string(5) "ERROR"
  ["Notifications"]=>
  object(stdClass)#30 (6) {
    ["Severity"]=>
    string(5) "ERROR"
    ["Source"]=>
    string(4) "ship"
    ["Code"]=>
    string(4) "3630"
    ["Message"]=>
    string(53) "Action type TRANSFER is not allowed for this request."
    ["LocalizedMessage"]=>
    string(53) "Action type TRANSFER is not allowed for this request."
    ["MessageParameters"]=>
    object(stdClass)#31 (2) {
      ["Id"]=>
      string(6) "ACTION"
      ["Value"]=>
      string(8) "TRANSFER"
    }
  }
  ["Version"]=>
  object(stdClass)#32 (4) {
    ["ServiceId"]=>
    string(4) "ship"
    ["Major"]=>
    int(12)
    ["Intermediate"]=>
    int(1)
    ["Minor"]=>
    int(0)
  }
}

**Comment by JeremyDunn** [comment]
@dakhnod I fixed the ship.php example.

I changed it to use the 'processShipment' endpoint. If all you're trying to do is create a shipment, this should point you in the right direction.

It appears that the create pending shipment functionality was moved to the "Open Ship Service" (which isn't included in this project yet).

**Comment by JeremyDunn** [comment]
I assigned an issue to myself to add OpenShip web service. https://github.com/JeremyDunn/php-fedex-api-wrapper/issues/20

Closing this out.
