### ISSUE TITLE
FedEx will only accept TLSv1.2 connections, is this handled in this wrapper project?

### ISSUE THREAD

**Issue by dhanapal-yaali** [JeremyDunn/php-fedex-api-wrapper#182]
Effective September 30, 2021, FedEx will only accept TLSv1.2 connections.If your FedEx solution is still using the Transport Layer Security (TLS) version 1.0 or 1.1 protocol, you will experience service disruptions.

**Comment by Niji-Bemani** [comment]
How could we know which version is used ?
