### ISSUE TITLE
Authentication Failed

### ISSUE THREAD

**Issue by Muhammadzaidgul** [JeremyDunn/php-fedex-api-wrapper#185]
I have placed all the four required 'FEDEX_KEY', 'FEDEX_PASSWORD', 'FEDEX_ACCOUNT_NUMBER', and 'FEDEX_METER_NUMBER' correctly but still facing authentication failed message error code '1000'. Would be highly grateful for any assistance.

**Comment by ahkhan97** [comment]
any update on this error? i am also stuck here right now.. placed every thing as per instructions

**Comment by ahkhan97** [comment]
nvm, i just created a new test account on fedex and used those keys and credentials and i have successfully generated a label! Cheers to the API creator!
![fedex-label](https://user-images.githubusercontent.com/56297230/151617412-17c3f0f9-6fcb-4832-b664-d10685fc5e53.PNG)
