### ISSUE TITLE
How to set PurchaseOrder in label

### ISSUE THREAD

**Issue by smitakartit** [JeremyDunn/php-fedex-api-wrapper#194]
I got function setPurchaseOrderNumber(). but how to impliment this

**Comment by TheGr8** [comment]
I am not sure where you see the setPurchaseOrderNumber function. Here's how I do it, I believe I got this code from samples. 
`
$refPO = new ComplexType\CustomerReference();
$refPO ->setCustomerReferenceType('P_O_NUMBER')
  ->setValue('123456');
...
//Reference numbers are assigned to the first ITEM
$item = new ComplexType\RequestedPackageLineItem();
$item
	->setWeight($itemWeight)
	->setCustomerReferences([$refPO])
	->setInsuredValue($itemValue)
	->setSequenceNumber($item_seq);
 `
