### ISSUE TITLE
Package Types and Weight limit issue on Rate request

### ISSUE THREAD

**Issue by harisnano** [JeremyDunn/php-fedex-api-wrapper#196]
1. FEDEX_ENVELOPE doesn't return the rate request. it return "There are no valid services available."
2. For a single package the weight limit should be 50 lbs but you can't do more than 20 lbs when the packaging type is a Fedex box.
3. For weight more then 20lbs you have to use YOUR_PACKAGING

FEDEX_10KG_BOX - Weight limit for a single package: 50 lbs
FEDEX_25KG_BOX - Weight limit for a single package: 50 lbs
FEDEX_BOX - Weight limit for a single package: 50 lbs
FEDEX_EXTRA_LARGE_BOX - Weight limit for a single package: 50 lbs
FEDEX_LARGE_BOX - Weight limit for a single package: 50 lbs
FEDEX_MEDIUM_BOX - Weight limit for a single package: 50 lbs
FEDEX_PAK - Weight limit for a single package: 50 lbs
FEDEX_SMALL_BOX - Weight limit for a single package: 50 lbs
FEDEX_TUBE - Weight limit for a single package: 50 lbs
FEDEX_ENVELOPE - Weight limit for a single package: 10 lbs (can only send one package per shipment)
YOUR_PACKAGING - Weight limit for a single package: 2200 lbs

**Comment by TheGr8** [comment]
For the envelope option, I am using 0.5 lbs, which works for me. I am not sure how it's even possible to put 10 lbs of stuff in FedEx envelope, it would have to be a heavy metal plate :)

**Comment by harisnano** [comment]
If you look at the FedEx Calculator it allows max weight of 10 lbs for envelope and only 1 package for the shipment
![Screenshot from 2021-12-16 17-05-12](https://user-images.githubusercontent.com/5612515/146456092-821169f0-1323-46db-a082-aac782f143f6.png)

**Comment by TheGr8** [comment]
Ha... interesting, they must have just recently changed it. When I was developing my solution I was using the old calculator, it looks like it's still available here - https://www.fedex.com/ratefinder/standalone
With that tool, it will not accept an envelope even with 1lb weight, so I advised my users to put 0.5lbs for the envelope and that solved it for us.
I wonder if their new calculator is still glitchy.
