### ISSUE TITLE
Update all WSDL files and regenerate code

### ISSUE THREAD

**Issue by JeremyDunn** [JeremyDunn/php-fedex-api-wrapper#20]
https://www.fedex.com/us/developer/web-services/process.html?tab=tab1#app-tab2

Standard Services:

- [x] ValidationAndCommitmentService (v8)
- [x] TrackService (v14)
- [x] RateService (v22)
- [x] LocationsService (v7)
- [x] CountryService (v6)

Advanced Services:
- [x] AddressValidationService (v4)
- [x] CloseService (v5)
- [x] DGDS - Upload Dangerous Goods Commodities Data (v3)
- [x] DGLD - Retrieve Dangerous Goods Shipments (v1)
- [x] InFlightShipmentService (v1)
- [x] OpenShipService (v11)
- [x] PickupService (v15)
- [x] ShipService (v21)
- [x] UploadDocumentService (v11)
- [x] ASYNC Transaction Service (v4)

**Comment by xiaozha87** [comment]
update RateService (v20)??? code is v10

**Comment by puneetverma05** [comment]
@JeremyDunn any Update on this enhancement ? :)

**Comment by guillaumenel** [comment]
Howdy. I had to regenerate Rates service to get PreferredCurrency (which require the new property SimpleType\RateRequestType::_PREFERRED) to be set. 
We're at v22 from release's version of v10. I think it's time :)

I doubt much else the documentation/examples needs to change as a result.
Bumping for future users.

**Comment by vasikgreif** [comment]
@JeremyDunn Hello, any chance to update the WDSL? I currently need the Ship API v21. Or, is there any guide on how to update the files?

**Comment by guillaumenel** [comment]
@vasikgreif 

This is some time ago, but from what I recall:
1. I copied the new files I needed(in my case the RateService v22 update) into the "_wsdl" directly, i.e.:
`php-fedex-api-wrapper-master/src/FedEx/_wsdl/RateService_v22.wsdl`

2. Then I searched for the old service wsdl name within GenerateCode.php found at...
`php-fedex-api-wrapper-master/util/Cli/GenerateCode/Command/GenerateCode.php`
...and updated to my new version. It now read like this:
`$wsdlPath = $fedexSrcDir . '/_wsdl/RateService_v22.wsdl';`

3 (?). I think i ran a `composer install` from the project path to get the code generation's dependencies. I ignored the 'abandoned' warnings which came up.

4. From within the project root directly I launched `generate-classes-from-wsdls.php` with a `generate` parameter, i.e.
`php -f ./util/generate-classes-from-wsdls.php generate`
If `php` can not be found, use the absolute path to your php executable.

This will regenerate all the relevant PHP classes from wsdl to:
`php-fedex-api-wrapper-master/src/FedEx`

4. Manually include the library into your project using your new source. 👍

**Comment by vasikgreif** [comment]
@guillaumenel Very cool, gonna give it a try! Lets see if @JeremyDunn shows up here to give us good news about updating the code here!

**Comment by JeremyDunn** [comment]
Hey, sorry for the delay on getting these updated.  I did make some progress updating these, but I still need to update the rate service examples before I merge them into master.

This branch has RateService 22: https://github.com/JeremyDunn/php-fedex-api-wrapper/tree/update-services

**Comment by vasikgreif** [comment]
@JeremyDunn Thanks for the update! What I need is the Shipping service v21, and the Pickup service v15. Any chance to get those?

**Comment by JeremyDunn** [comment]
Yeah, the branch I mentioned above also has those updates (Ship Service v21 and Pickup Service v15).

**Comment by vasikgreif** [comment]
@JeremyDunn Thanks, very cool!

**Comment by mehgcap** [comment]
I'm working on a web service for the company I work for, and it has to do FedEx. My boss says we need to support One Rate, which isn't in the current crop of WSDLs in the release version of this API wrapper. Are there any plans to release an update with the most recent WSDLs included? Thanks.

**Comment by JeremyDunn** [comment]
I haven't had much time to maintain this library lately, but I may spend some time on it later this month.

In the mean time, you could regenerate the code for your newer .wsdl file using the instructions @guillaumenel posted above: https://github.com/JeremyDunn/php-fedex-api-wrapper/issues/20#issuecomment-349108784

**Comment by mehgcap** [comment]
Thanks, I'm not sure how I missed that comment. :) I've just updated every WSDL that FedEx has an update for, and am now making a copy of the newly generated code outside of Composer's folder. This will be a dumb question, but I'm no PHP expert: how do I include the library once I take it out of the vendor folder? I have no other autoload.php file and wouldn't know how to make one. Or, can I safely work off the Compoer copy? If so, I'll have to rework my .gitignore, but that should be easy enough.

**Comment by JeremyDunn** [comment]
I would fork this repo, make the code changes and commit to your fork.  Then update your composer file to pull in your repo instead of this package.  See: https://getcomposer.org/doc/05-repositories.md#loading-a-package-from-a-vcs-repository

**Comment by mistris** [comment]
@JeremyDunn Hi! When will all updated wsdl files be in master branch?

**Comment by JeremyDunn** [comment]
All services have been updated to their latest versions and merged into master.
