### ISSUE TITLE
CustomsClearanceDetail

### ISSUE THREAD

**Issue by cambur** [JeremyDunn/php-fedex-api-wrapper#206]
Thank you for this great package.
Sorry to bother you but just wanted to know if you any examples of CustomsClearanceDetail

**Comment by JeremyDunn** [comment]
Hey @cambur unfortunately I don't have any examples of that offhand. Maybe someone else can help or submit an example as a PR?

**Comment by cambur** [comment]
Perfect. I am building one. I will push it

**Comment by cambur** [comment]
I was able to figure this one out, but attching a commercial invoice to an open shipment seems much more complicated :-/ Is something about **ConfirmConsolidationRequest** but I have no idea.
