### ISSUE TITLE
"Payor country code must match either Origin or Destination country code"

### ISSUE THREAD

**Issue by dakhnod** [JeremyDunn/php-fedex-api-wrapper#21]
after editing all the adress data in examples/ship.php so that the package is sent from germany ('DE' countrycode) to germany, i get the errormessage "ShippingChargesPayment - Payor country code must match either Origin or Destination country code". although in the code the paying party is set equal to the shipper e.g. the origin.

**Comment by JeremyDunn** [comment]
This error message is being returned from FedEx, but I don't know what it means exactly.
https://www.fedex.com/us/developer/WebHelp/ws/2014/dvg/WS_DVG_WebHelp/Ship_Service_and_Open_Shipping_Error_Messages.htm

I can reproduce the error by updating the addresses as well. My FedEx account # is registered with a US address.  Maybe that has something to do with it?

Open a ticket with FedEx developer support and send them your raw request data.

`$shipService->getSoapClient()->__getLastRequest();`

http://www.fedex.com/us/developer/get-support.html

**Comment by JeremyDunn** [comment]
I'm closing this out, but I'm curious to know what FedEx support had to say about this error message.
