### ISSUE TITLE
Add support for REST API?

### ISSUE THREAD

**Issue by greggles** [JeremyDunn/php-fedex-api-wrapper#214]
Adding this issue to track the idea of the REST API.

FedEx is starting to encourage customers to move to the REST API by claiming they will turn off the SOAP API on February 28, 2024.  (See [this issue in the python repository](https://github.com/python-fedex-devs/python-fedex/issues/170)).

Do you plan to add support for the REST API into the PHP library?

**Comment by greggles** [comment]
For anyone else searching who stumbles upon this issue, there is also this relatively new repo that I have not tested myself: https://github.com/WhatArmy/FedexRest

**Comment by greggles** [comment]
It's...not stale?

**Comment by greggles** [comment]
I think it's important this stays open since it's likely to become more pressing as the EOL of SOAP approaches in the next months/years. I plan to comment "activity for visibility" to keep it open. I'm happy to be corrected if that action seems inappropriate in some way. Thanks.

**Comment by greggles** [comment]
Same reasoning as last time, although now https://github.com/WhatArmy/FedexRest has more features merged into it.

**Comment by cambur** [comment]
it would be awesome to add rest support...so I dont have to rewrite the whole integration again

**Comment by cambur** [comment]
I mean, I already my integration with this package, would be amazing that it generated a REST request instead of an XML, I am not asking anything to the developer, this is open source. I am just wondering if anyone else is facing the same issue.

**Comment by jaminion** [comment]
FedEx has announced the EOL of their SOAP apis for May 15, 2024.

https://www.fedex.com/en-us/developer/announcements.html#web-services

**Comment by greggles** [comment]
Thanks for documenting that here @jaminion. 

We've been using https://github.com/WhatArmy/FedexRest for several months. That could be a good thing to document in the README here.
