### ISSUE TITLE
Please remove /doc folder from the project

### ISSUE THREAD

**Issue by gplcart** [JeremyDunn/php-fedex-api-wrapper#22]
Hello
The doc folder contents A LOT of API files which are useless in real life. Also NetBeans marks them as "error parsing file"

**Comment by JeremyDunn** [comment]
Yes I agree they shouldn't be versioned. Luckily I had already started doing this. I cherry-picked into a new PR.  #23

**Comment by gplcart** [comment]
And big thanks for your hard work. Native Fedex API is a nightmare :)
