### ISSUE TITLE
Authentication Failed

### ISSUE THREAD

**Issue by gplcart** [JeremyDunn/php-fedex-api-wrapper#24]
Hello
I'm trying to rate parcels using this example https://github.com/JeremyDunn/php-fedex-api-wrapper/blob/master/examples/rate-service-request.php
I'm using test credentials I got from FedEx + account password for FEDEX_PASSWORD constant
The resulting response object looks like

```
public HighestSeverity -> string(5) "ERROR"
public Notifications -> stdClass(4)
public Severity -> string(5) "ERROR"
public Source -> string(4) "prof"
public Code -> string(4) "1000"
public Message -> string(21) "Authentication Failed"
public TransactionDetail -> stdClass(1)
public CustomerTransactionId -> string(28) "Testing Rate Service request"
public Version -> stdClass(4)
public ServiceId -> string(3) "crs"
public Major -> integer10
public Intermediate -> integer0
public Minor -> integer0
```
Any ideas how to fix it please? Do I need to set manually a particular test url via 

`$rateServiceRequest->getSoapClient()->__setLocation('https://wsbeta.fedex.com:443/web-services');`

or test mode is enabled by default?

**Comment by gplcart** [comment]
Ok, fixed
Just got E-mail from FedEx support, there is TEST password. And yes, testmode is enabled by default

**Comment by chrismagneti** [comment]
How do you disable test mode?
