### ISSUE TITLE
How to generate Labels ?

### ISSUE THREAD

**Issue by abhishekdeshkar** [JeremyDunn/php-fedex-api-wrapper#27]
Hi,

How can I generate the labels ?

**Comment by JeremyDunn** [comment]
Look at the create shipment example:
https://github.com/JeremyDunn/php-fedex-api-wrapper/blob/master/examples/ship.php#L75

**Comment by abhishekdeshkar** [comment]
@JeremyDunn : Thank You! Why this is not working ? composer require jeremy-dunn/php-fedex-api-wrapper

**Comment by JeremyDunn** [comment]
This should work now.  I created a 1.0 tag to indicate a stable release.
