### ISSUE TITLE
Array config

### ISSUE THREAD

**Issue by fjqtp** [JeremyDunn/php-fedex-api-wrapper#29]
Hello,

in the latest version I'm not able to config request with array as I did previously:

```
$raterequest = new RateRequest([
            'WebAuthenticationDetail' => new WebAuthenticationDetail([
                'UserCredential'    => new WebAuthenticationCredential([
                    'Key'      => '***',
                    'Password' => '***',
                ])
            ]),
...
]);
```

new syntax expects I'll be doing something like this:

```
$userCredential
    ->setKey(FEDEX_KEY)
    ->setPassword(FEDEX_PASSWORD);
```

Can you please return ability to config with arrays or say me what I'm doing wrong now?

**Comment by JeremyDunn** [comment]
Sorry my latest release broke backward compatibility.  Please use release 1.1
https://github.com/JeremyDunn/php-fedex-api-wrapper/releases/tag/1.1

**Comment by fjqtp** [comment]
Big thanks, works now!
