### ISSUE TITLE
how to create test shipment request

### ISSUE THREAD

**Issue by Harsukh21** [JeremyDunn/php-fedex-api-wrapper#30]
Hi,
how to create test shipment request in fexed.
i mean how to pass beta envirentment variable in our shipmet request, because i have authentication fail error and right now i use test FEDEX_API_KEY, FEDEX_API_PASSWORD, FEDEX_ACCOUNT_NO, FEDEX_METER_NO for create shipment request but it show me authentication fail error

Here My Code

                $userCredential = new \FedEx\ShipService\ComplexType\WebAuthenticationCredential();
		$userCredential
		    ->setKey(config('fedex.key'))
		    ->setPassword(config('fedex.password'));
		$webAuthenticationDetail = new \FedEx\ShipService\ComplexType\WebAuthenticationDetail();
		$webAuthenticationDetail->setUserCredential($userCredential);

		$clientDetail = new \FedEx\ShipService\ComplexType\ClientDetail();
		$clientDetail
		    ->setAccountNumber(config('fedex.account'))
		    ->setMeterNumber(config('fedex.meter'));

		$version = new \FedEx\ShipService\ComplexType\VersionId();
		$version
		    ->setMajor(12)
		    ->setIntermediate(1)
		    ->setMinor(0)
		    ->setServiceId('ship');

		$shipperAddress = new \FedEx\ShipService\ComplexType\Address();
		$shipperAddress
		    ->setStreetLines(array(
		        '12345 Main Street',
		        'STE 810'
		    ))
		    ->setCity('Anytown')
		    ->setStateOrProvinceCode('NY')
		    ->setPostalCode('12345')
		    ->setCountryCode('US');

		$shipperContact = new \FedEx\ShipService\ComplexType\Contact();
		$shipperContact
		    ->setCompanyName('Company Name')
		    ->setEMailAddress('test@example.com')
		    ->setPersonName('Person Name')
		    ->setPhoneNumber(('123-123-1234'));

		$shipper = new \FedEx\ShipService\ComplexType\Party();
		$shipper
		    ->setAccountNumber(config('fedex.account'))
		    ->setAddress($shipperAddress)
		    ->setContact($shipperContact);

		$recipientAddress = new \FedEx\ShipService\ComplexType\Address();
		$recipientAddress
		    ->setStreetLines(array('54312 1st Ave'))
		    ->setCity('Anytown')
		    ->setStateOrProvinceCode('NY')
		    ->setPostalCode('12345')
		    ->setCountryCode('US');

		$recipientContact = new \FedEx\ShipService\ComplexType\Contact();
		$recipientContact
		    ->setPersonName('Contact Name');

		$recipient = new \FedEx\ShipService\ComplexType\Party();
		$recipient
		    ->setAddress($recipientAddress)
		    ->setContact($recipientContact);

		$labelSpecification = new \FedEx\ShipService\ComplexType\LabelSpecification();
		$labelSpecification
		    ->setLabelStockType(new \FedEx\ShipService\SimpleType\LabelStockType(\FedEx\ShipService\SimpleType\LabelStockType::_PAPER_7X4point75))
		    ->setImageType(new \FedEx\ShipService\SimpleType\ShippingDocumentImageType(\FedEx\ShipService\SimpleType\ShippingDocumentImageType::_PDF))
		    ->setLabelFormatType(new \FedEx\ShipService\SimpleType\LabelFormatType(\FedEx\ShipService\SimpleType\LabelFormatType::_COMMON2D));

		$requestedShipment = new \FedEx\ShipService\ComplexType\RequestedShipment();
		$requestedShipment->setShipTimestamp(date('c'));
		$requestedShipment->setDropoffType(new \FedEx\ShipService\SimpleType\DropoffType(\FedEx\ShipService\SimpleType\DropoffType::_REGULAR_PICKUP));
		$requestedShipment->setServiceType(new \FedEx\ShipService\SimpleType\ServiceType(\FedEx\ShipService\SimpleType\ServiceType::_FEDEX_GROUND));
		$requestedShipment->setPackagingType(new \FedEx\ShipService\SimpleType\PackagingType(\FedEx\ShipService\SimpleType\PackagingType::_YOUR_PACKAGING));
		$requestedShipment->setShipper($shipper);
		$requestedShipment->setRecipient($recipient);
		$requestedShipment->setLabelSpecification($labelSpecification);
		$requestedShipment->setRateRequestTypes(array(new \FedEx\ShipService\SimpleType\RateRequestType(\FedEx\ShipService\SimpleType\RateRequestType::_ACCOUNT)));
		$requestedShipment->setPackageCount(1);

		$createPendingShipmentRequest = new \FedEx\ShipService\ComplexType\CreatePendingShipmentRequest();
		// dd($webAuthenticationDetail::_NAME);
		$createPendingShipmentRequest->setWebAuthenticationDetail($webAuthenticationDetail);
		$createPendingShipmentRequest->setClientDetail($clientDetail);
		$createPendingShipmentRequest->setVersion($version);
		$createPendingShipmentRequest->setRequestedShipment($requestedShipment);
		// dd($createPendingShipmentRequest);

		$shipService = new \FedEx\ShipService\Request();
		$shipService->getSoapClient()->__setLocation('https://ws.fedex.com:443/web-services/ship');
		$result = $shipService->getCreatePendingShipmentReply($createPendingShipmentRequest);
		dd($result);

Please help me

**Comment by muhiddingithub** [comment]
May it help you [http://stackoverflow.com/questions/2013657/issues-using-a-fedex-webservice-via-wsdl-soap](url)

**Comment by JeremyDunn** [comment]
@Harsukh21 **Remove** this line from your code above.  Then it will use the beta environment.

`$shipService->getSoapClient()->__setLocation('https://ws.fedex.com:443/web-services/ship');`
