### ISSUE TITLE
When request Create Shipment error SoapFault fault

### ISSUE THREAD

**Issue by muhiddingithub** [JeremyDunn/php-fedex-api-wrapper#34]
```
public function getCreatePendingShipmentReply(ComplexType\CreatePendingShipmentRequest $createPendingShipmentRequest)
    {
        return $this->getSoapClient()->createPendingShipment($createPendingShipmentRequest->toArray());
    }
```

**Comment by JeremyDunn** [comment]
Please see this closed ticket: https://github.com/JeremyDunn/php-fedex-api-wrapper/issues/18

The create pending shipment functionality was moved to a different service which has not yet been implemented in this library.  However if you're trying to create a non-pending shipment, use the `getProcessShipement()` method.

https://github.com/JeremyDunn/php-fedex-api-wrapper/blob/master/src/FedEx/ShipService/Request.php#L48
