### ISSUE TITLE
Problem with installation 

### ISSUE THREAD

**Issue by guancarlos** [JeremyDunn/php-fedex-api-wrapper#35]
i'm trying to install the package with 
`composer require JeremyDunn/php-fedex-api-wrapper`

and i have this error

` [InvalidArgumentException]                                                   
  Could not find package JeremyDunn/php-fedex-api-wrapper at any version for   
  your minimum-stability (stable). Check the package spelling or your minimum  
  -stability                                                                   
               `

i was trying in composer.json with 
`"jeremydunn/php-fedex-api-wrapper":"@dev",`
or
`"JeremyDunn/php-fedex-api-wrapper":"dev"`
and show me this error:
`Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package jeremydunn/php-fedex-api-wrapper could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
`

i  have laravel 5.4, thanks

**Comment by JeremyDunn** [comment]
The above worked for me:
`composer require JeremyDunn/php-fedex-api-wrapper`

Can you please try again? If that doesn't work, try adding the following line to your composer.json "require" section: 
`"jeremy-dunn/php-fedex-api-wrapper": "^1.1"`

**Comment by guancarlos** [comment]
with `composer require JeremyDunn/php-fedex-api-wrapper`
![screenshot from 2017-06-13 09-01-46](https://user-images.githubusercontent.com/8834726/27086356-9256b5ca-5017-11e7-8a02-12a6c7956ce4.png)
but with  `"jeremy-dunn/php-fedex-api-wrapper": "^1.1"` in composer.json it worked ! 
thank u very  much

**Comment by satyajit9830** [comment]
I am having the same issue. pls help me to fix it
![screenshot_4](https://user-images.githubusercontent.com/763412/38771600-9cb37b76-4043-11e8-9bbe-a46cf1951b2f.jpg)
