### ISSUE TITLE
Batch Tracking

### ISSUE THREAD

**Issue by AlexeyKosov** [JeremyDunn/php-fedex-api-wrapper#46]
Is it possible to track multiple shipments at once? 
The doc says a request can contain up to 30 items to track https://www.fedex.com/us/developer/WebHelp/ws/2017/html/WebServicesHelp/WSDVG_US_CA/index.htm#wsdvg/Batch_Tracking.htm

**Comment by JeremyDunn** [comment]
Hi, this library is currently using Track Service version 5, but the current version from FedEx is 14.  I will update this service in the near future and provide an updated example.

See also: https://github.com/JeremyDunn/php-fedex-api-wrapper/issues/20

**Comment by ipanardian** [comment]
Hi, is there any update for batch tracking?

**Comment by JeremyDunn** [comment]
Latest version of tracking service has been merged into master. Closing.
