### ISSUE TITLE
Example for CourierDispatchService

### ISSUE THREAD

**Issue by poovarasanvasudevan** [JeremyDunn/php-fedex-api-wrapper#59]
Can you Please Provide an Example for CourierDispatchService..

Thanks.

**Comment by JeremyDunn** [comment]
Sorry, I don't have any information about the CourierDispatchService from FedEx. In fact, I can't find any details about this service in the current Web Services Developer Guide.

https://images.fedex.com/templates/components/apps/wpor/secure/downloads/pdf/201707/FedEx_WebServices_DevelopersGuide_v2017.pdf
