### ISSUE TITLE
How to resolve - Error::Customs Clearance Detail is required

### ISSUE THREAD

**Issue by manojsinghadha** [JeremyDunn/php-fedex-api-wrapper#60]
Hi,
I am from India and trying to use your fedex api service class - ShipService\Request()
But facing error like ::

[Severity] => ERROR
[Source] => ship
[Code] => 2449
[Message] => Customs Clearance Detail is required
[LocalizedMessage] => Customs Clearance Detail is required

I am trying to generate shipment for local indian address with following parameters: 

DropoffType::_REGULAR_PICKUP
ServiceType::_STANDARD_OVERNIGHT
PackagingType::_YOUR_PACKAGING
RateRequestType::_ACCOUNT

I am not sure what extra setting i need to make in class code to overcome this error.
Would you please guide me.

Thanks & Regards

**Comment by JeremyDunn** [comment]
Sorry, I don't know. I've never used CustomsClearanceDetail in my ship requests before. Please refer to the official FedEx Web Services developer guide.

https://images.fedex.com/templates/components/apps/wpor/secure/downloads/pdf/201707/FedEx_WebServices_DevelopersGuide_v2017.pdf

I can tell you that the CustomsClearanceDetail should be attached to your `RequestedShipment` object.  So, using the [ship.php](https://github.com/JeremyDunn/php-fedex-api-wrapper/blob/master/examples/ship.php#L103) example, you would add line like `$requestedShipment->setCustomsClearanceDetail()` `CustomsClearanceDetail` would be populated with all of your customs clearance data.

See also: 
https://github.com/JeremyDunn/php-fedex-api-wrapper/blob/master/src/FedEx/ShipService/ComplexType/RequestedShipment.php#L263

https://github.com/JeremyDunn/php-fedex-api-wrapper/blob/master/src/FedEx/ShipService/ComplexType/CustomsClearanceDetail.php

**Comment by JuanGamarraDev** [comment]
Please.
Some example of code?. I've tried it in many ways and none of it works

$requestedShipment->setCustomsClearanceDetail()
