### ISSUE TITLE
How to Send Custom Values Parameters while request shipment?

### ISSUE THREAD

**Issue by rkishir** [JeremyDunn/php-fedex-api-wrapper#63]
Hello Guys, 
I have implemented it in my project but getting an error message "Custom Values required" when requested for international shipment. How can I pass custom value parameters? I tried  by adding this code: 
 $requestedPackageLineItem1->CustomsValue->Value = $itemdetails['CustomsValue'];
 OR
$createOpenShipmentRequest->RequestedShipment->CustomsClearanceDetail =  $itemdetails['CustomsValue'];

Please check my controller code here: https://www.screencast.com/t/xFtBwTvj

But both are not working. Please help

**Comment by kruegge82** [comment]
you find a solution?

**Comment by ericmuigai** [comment]
@kruegge82 @rkishir found a solution?

**Comment by JuanGamarraDev** [comment]
any example?

**Comment by JuanGamarraDev** [comment]
@rkishir @kruegge82 @ericmuigai @JeremyDunn found a solution?

I have the same problem.
I hope you can help me.
Thank you.

**Comment by JuanGamarraDev** [comment]
This worked for me:

`<?php

use FedEx\ShipService;
use FedEx\ShipService\ComplexType;
use FedEx\ShipService\SimpleType;

$CustomsClearanceDetail = [
	'DutiesPayment' => new ComplexType\Payment([
		'PaymentType' => 'RECIPIENT', // valid values RECIPIENT, SENDER and THIRD_PARTY
//				'Payor' => new ComplexType\Payor([
//					'ResponsibleParty' => new ComplexType\Party([
//						'AccountNumber' => FEDEX_ACCOUNT_NUMBER, // OPTIONAL
//						'Contact' => new ComplexType\Contact([]),
//						'Address' => new ComplexType\Address([])
//					])
//				])
    ]),
	'DocumentContent' => 'NON_DOCUMENTS',
	'CustomsValue' => new ComplexType\Money([
		'Currency' => 'USD',
		'Amount' => 400.0
	]),
	'Commodities' => [
		[
			'NumberOfPieces' => 1,
			'Description' => 'Books',
			'CountryOfManufacture' => 'MX',
			'Weight' => array(
				'Units' => 'KG',
				'Value' => 1.0
			),
			'Quantity' => 4,
			'QuantityUnits' => 'EA',
			'UnitPrice' => array(
				'Currency' => 'USD',
				'Amount' => 100.000000
			),
			'CustomsValue' => array(
				'Currency' => 'USD',
				'Amount' => 400.000000
			)
		]
	],
	'ExportDetail' => new ComplexType\ExportDetail([
		'B13AFilingOption' => 'NOT_REQUIRED'
	])
];

$requestedShipment->setCustomsClearanceDetail(new ComplexType\CustomsClearanceDetail(
    $CustomsClearanceDetail
));`

**Comment by Orion7agency** [comment]
Guys, I am getting a different tracking number on the label vs the tracking number when I am creating a shipment. Can you please tell me how do I pass the tracking parameters while creating the shipment?
