### ISSUE TITLE
Generate bar codes after creating shipment

### ISSUE THREAD

**Issue by rkang30** [JeremyDunn/php-fedex-api-wrapper#64]
Hi,

Thank you for creating a beautiful php wrapper for fedex. I was so happy to see this. One question I have is that how I can generate a label with bar codes after creating a new shipment.

Thanks in advance,

Ryan

**Comment by rkang30** [comment]
Please ignore this. I just found that I can generate label which has a bar code.

**Comment by Hedzerg** [comment]
@rkang30 how did you generated a label only with the barcode? Can you point me in the right direction? Should you create a open shipment or a pending?
