### ISSUE TITLE
LTL Rate Requests Example?

### ISSUE THREAD

**Issue by Critter** [JeremyDunn/php-fedex-api-wrapper#69]
I don't suppose anybody has an example of a rate request for LTL?

**Comment by Critter** [comment]
@donttalktorobots kind of... I ended up splitting my ground and ltl calls. My ground calls use this wrapper and my ltl calls are just with the basic fedex soap example they have for freight.

**Comment by donttalktorobots** [comment]
@Critter Can you point me in the direction of the Fedex Soap example?  I have been trying alot of different things, but haven't gotten anything to work.

**Comment by Critter** [comment]
@donttalktorobots I've attached the files here...
[RateWebServiceClient.zip](https://github.com/JeremyDunn/php-fedex-api-wrapper/files/2059358/RateWebServiceClient.zip)

**Comment by donttalktorobots** [comment]
@Critter Thanks!
