### ISSUE TITLE
Fedex envelope packaging type example

### ISSUE THREAD

**Issue by Jaicika** [JeremyDunn/php-fedex-api-wrapper#71]
Hi,

I am having some issue while selecting Packaging Type as "Envelop". Its giving an error "There are no valid services available". Can you please provide me an example for the same so that I can get to know how to use it?

Thanks.

**Comment by JeremyDunn** [comment]
Try setting the `PhysicalPackaging` for your `RequestedPackageLineItem`.

Using the existing `rate-request.php` to get started:
https://github.com/JeremyDunn/php-fedex-api-wrapper/blob/master/examples/rate-request.php#L60

You should be able to set the package type like so:

```php
$rateRequest->RequestedShipment->RequestedPackageLineItems[0]->PhysicalPackaging = SimpleType\PhysicalPackagingType::_ENVELOPE
```
