### ISSUE TITLE
PNG Label

### ISSUE THREAD

**Issue by abnoy** [JeremyDunn/php-fedex-api-wrapper#74]
I'm having trouble retrieving a label as a PNG.  PDF and ZPLII work fine but the response is blank when I use PNG.  

I'm using the example in:
https://github.com/JeremyDunn/php-fedex-api-wrapper/blob/master/examples/ship.php#L75

```php
<?php
$labelSpecification = new ComplexType\LabelSpecification();
$labelSpecification
    ->setLabelStockType(new SimpleType\LabelStockType(SimpleType\LabelStockType::_PAPER_4X6))
    ->setImageType(new SimpleType\ShippingDocumentImageType(SimpleType\ShippingDocumentImageType::_PNG))
    ->setLabelFormatType(new SimpleType\LabelFormatType(SimpleType\LabelFormatType::_COMMON2D));
```

**Comment by JeremyDunn** [comment]
No setting, this is what the FedEx web service returns.  Just `file_put_contents()` the image data itself.

Here's an example, but for a .pdf file.

https://github.com/JeremyDunn/php-fedex-api-wrapper/blob/master/examples/ship.php#L130-L131
