### ISSUE TITLE
where is an example on how to track?

### ISSUE THREAD

**Issue by magna25** [JeremyDunn/php-fedex-api-wrapper#8]
as the title says, where is the example to track a package?

**Comment by filipp-qoma** [comment]
Yeap, I also want to see an example of how to use your lib =)

**Comment by JeremyDunn** [comment]
@filipp-qoma To begin, you can look in the 'examples' folder. https://github.com/JeremyDunn/php-fedex-api-wrapper/tree/master/examples

**Comment by filipp-qoma** [comment]
oops, sorry, and thank you, @JeremyDunn!)
