### ISSUE TITLE
Soap Error

### ISSUE THREAD

**Issue by docelmo** [JeremyDunn/php-fedex-api-wrapper#81]
Anyone have any thoughts on why I keep getting this?

Error: [SoapFault] SOAP-ERROR: Encoding: Element 'Major' has fixed value '2' (value '4' is not allowed)

I am not 100% on what to do to fix it.  

Brian

**Comment by AbhayLodhi** [comment]
You have to try **Major=>'21'**.Major is the wsdl version code .

$request['Version'] = array(
	'ServiceId' => 'ship', 
	'Major' => '21', 
	'Intermediate' => '0', 
	'Minor' => '0'
);
