### ISSUE TITLE
API with Proxy

### ISSUE THREAD

**Issue by docelmo** [JeremyDunn/php-fedex-api-wrapper#83]
Greetings..  Im having a bit of an issue.  I have to install the API behind a proxy.  I have setup the proxy by modifying the code but it appears not to be working as it times out on the gateway.  Has anyone used this API behind a proxy?  If so, can you cite the code changes made to make it work?

**Comment by JeremyDunn** [comment]
If using a proxy means you have a different URL for the Web service endpoint, you can create your own instance of the SoapClient that each Request object uses.

For example:
```php
$soapClient = new \SoapClient('https://custom-url-to-proxy.wsdl', ['trace' => true]);
$request = new \FedEx\RateService\Request($soapClient);
```
