### ISSUE TITLE
Adding Logo to shipping label

### ISSUE THREAD

**Issue by docelmo** [JeremyDunn/php-fedex-api-wrapper#84]
Has anyone tried to customize the label with a logo?  I was looking at the fedex api documentation and it spoke to it but I cant make heads/tails on how to actually do it.  If you have can you post a code example?

**Comment by dimitris444** [comment]
were you lucky enough to find a way to print your label? I am stuck at the same point.... i can't add my logo into the label....

**Comment by matcsa** [comment]
Nope.  Still no clue.  Documentation is clugey both from fedex and the
wrapper.
