### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by noydarly** [JeremyDunn/php-fedex-api-wrapper#85]
Hello.
This is not an issue, just, I've got one question for you.
You did a really really great job here.
So what I want to ask is, is it possible to validate Saturday Service?
I got how to create a Saturday Service Request through your code, but is there any way to validate it separately?
I really look forward to haring back from you.
Thank you.
Kind Regards.
Noy.

**Comment by JeremyDunn** [comment]
I don't have an example of this, but you should be able to validate the shipment before creating it using a `ValidateShipmentRequest`. See: https://github.com/JeremyDunn/php-fedex-api-wrapper/blob/master/src/FedEx/ShipService/Request.php#L103
