### ISSUE TITLE
changing values cause error

### ISSUE THREAD

**Issue by ccnkemdilim** [JeremyDunn/php-fedex-api-wrapper#94]
I made changes to values in recipients address and i got errors 

$recipientAddress = new ComplexType\Address();
$recipientAddress
    ->setStreetLines(['125 Southam hall'])
    ->setCity('Ottawa')
    ->setStateOrProvinceCode('ON')
    ->setPostalCode('20171')
    ->setCountryCode('US');

I am not sure why this would give me "mismatch" errors

Please help

**Comment by TheGr8** [comment]
You have a Canadian city and province but USA country code and postal code.
