### ISSUE TITLE
Error in deleting pending shipment

### ISSUE THREAD

**Issue by ccnkemdilim** [JeremyDunn/php-fedex-api-wrapper#95]
Hi 
I keep getting this error when running delete-pending-shipment example
<pre>
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to FedEx\AbstractComplexType::populateFromStdClass() must be an instance of stdClass, null given, called in /php-fedex-api-wrapper/src/FedEx/ShipService/Request.php on line 92 and defined in /php-fedex-api-wrapper/src/FedEx/AbstractComplexType.php:139
Stack trace:
#0 /var/www/php-fedex-api-wrapper/src/FedEx/ShipService/Request.php(92): FedEx\AbstractComplexType->populateFromStdClass(NULL)
#1 /var/www/php-fedex-api-wrapper/examples/delete-pending-shipment.php(46): FedEx\ShipService\Request->getDeleteShipmentReply(Object(FedEx\ShipService\ComplexType\DeleteShipmentRequest))
#2 {main}
  thrown in /php-fedex-api-wrapper/src/FedEx/AbstractComplexType.php on line 139 </pre>

Thanks

**Comment by Vishnu-Selva-Kumar** [comment]
same error display in my project how to solve thsis
