### ISSUE TITLE
How to create return shipment label?

### ISSUE THREAD

**Issue by kaydee92** [JeremyDunn/php-fedex-api-wrapper#96]
Hi,
We have use your FedEx Sdk.
All things are working fine, but we don't know how to create return shipment label.
so is there any way to create that? if so, then please reply asap.
because we have already search on google, but  there is no proper example of this.

**Comment by kaydee92** [comment]
@JeremyDunn Can you please help me??

**Comment by dooferorg** [comment]
I'm also needing this.

I am not seeing any objects for the ReturnTagService even though it is in the FedEx WSDL

**Comment by dooferorg** [comment]
I did see there's a 'ReturnTagService' entry, so using the information in the FedEx Developer guide that might get you where you need to be. Making the request and setting the Address in a similar way to how the other requests are made.
