### ISSUE TITLE
How to do cancel shipment?

### ISSUE THREAD

**Issue by naumanpathan** [JeremyDunn/php-fedex-api-wrapper#97]
I have to need to cancel the shipment. I have found the example in your repo but in that example has a bug. The bug looks like :

Class 'FedEx\ShipService\ComplexType\CancelPendingShipmentRequest' not found

So, I have debugged the code and I have found no file available in ComplexType folder, name as CancelPendingShipmentRequest.php

So, can you please provide me that file asap.

thanks and regards.

**Comment by TheGr8** [comment]
I was curious, so I just took a look at this, since I am getting to the point where I will be calling this. It looks like this file was removed when while upgrading to v21 of Web Services :

https://github.com/JeremyDunn/php-fedex-api-wrapper/commit/d20cbb7d8402763e6acb0054bb2da49f04a50679#diff-944445786984ae3867e13286d40ba857

but also the reference to the file was removed from Request.php :
https://github.com/JeremyDunn/php-fedex-api-wrapper/commit/f440cc1b7efbc2dc01e50244436005a9b06dfd06#diff-18c96384e7a0f1f5a6e54d6572ff516c

So it looks like you may not have the latest /FedEx/ShipService/Request.php , make sure you update all files.

**Comment by osseonews** [comment]
Anybody figure this out? How do you cancel a shipment with the latest version? The file in the example repo to do this has a bug, as per above. What is an updated example to cancel a shipment?

**Comment by e-hop** [comment]
+1

**Comment by e-hop** [comment]
Solved

```
$cancelPendingShipmentRequest = new ComplexTypeShip\DeleteShipmentRequest();
$cancelPendingShipmentRequest->WebAuthenticationDetail->UserCredential->Key = env('FEDEX_KEY');
$cancelPendingShipmentRequest->WebAuthenticationDetail->UserCredential->Password =env('FEDEX_PASSWORD');
$cancelPendingShipmentRequest->ClientDetail->AccountNumber = env('FEDEX_ACCOUNT_NUMBER');
$cancelPendingShipmentRequest->ClientDetail->MeterNumber = env('FEDEX_METER_NUMBER');
$cancelPendingShipmentRequest->Version->ServiceId = 'ship';
$cancelPendingShipmentRequest->Version->Major = 23;
$cancelPendingShipmentRequest->Version->Intermediate = 0;
$cancelPendingShipmentRequest->Version->Minor = 0;
$cancelPendingShipmentRequest->TrackingId->TrackingNumber = $tracking_number;
$cancelPendingShipmentRequest->DeletionControl = 'DELETE_ALL_PACKAGES';

$shipServiceRequest = new RequestShip();
$cancelPendingShipmentReply = $shipServiceRequest->getDeleteShipmentReply($cancelPendingShipmentRequest);
```

**Comment by taviya** [comment]
This error occurs when I use the code above.

Fatal error:  Uncaught TypeError: Argument 1 passed to FedEx\AbstractComplexType::populateFromStdClass() must be an instance of stdClass, null given, called in C:\xampp\htdocs\fedex-api\src\FedEx\ShipService\Request.php on line 95 and defined in C:\xampp\htdocs\fedex-api\src\FedEx\AbstractComplexType.php:139
Stack trace:
#0 C:\xampp\htdocs\fedex-api\src\FedEx\ShipService\Request.php(95): FedEx\AbstractComplexType->populateFromStdClass(NULL)
#1 C:\xampp\htdocs\fedex-api\examples\cancel-pending-shipment.php(50): FedEx\ShipService\Request->getDeleteShipmentReply(Object(FedEx\ShipService\ComplexType\DeleteShipmentRequest))
#2 {main}
  thrown in C:\xampp\htdocs\fedex-api\src\FedEx\AbstractComplexType.php on line 139
